/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ijse.GearRentPro.view;

import com.ijse.GearRentPro.controller.BranchController;
import com.ijse.GearRentPro.dto.BranchDto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class BranchView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BranchView.class.getName());
    private BranchController branchController = new BranchController();

    /**
     * Creates new form BranchView
     */
    public BranchView() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblLocationtxt = new javax.swing.JTextField();
        iblContactNo = new javax.swing.JLabel();
        iblContactNotxt = new javax.swing.JTextField();
        iblUpdate = new javax.swing.JButton();
        iblSave = new javax.swing.JButton();
        iblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBranch = new javax.swing.JTable();
        iblBranchId = new javax.swing.JLabel();
        iblBranchName = new javax.swing.JLabel();
        iblBranchNametxt = new javax.swing.JTextField();
        iblBranchLoca = new javax.swing.JLabel();
        iblBranchIdtxt1 = new javax.swing.JTextField();
        iblBranchCode = new javax.swing.JLabel();
        iblBranchCodetxt = new javax.swing.JTextField();
        iblDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iblLocationtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblLocationtxt.addActionListener(this::iblLocationtxtActionPerformed);

        iblContactNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblContactNo.setText("Contact Number");

        iblContactNotxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblContactNotxt.addActionListener(this::iblContactNotxtActionPerformed);

        iblUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblUpdate.setText("Update");
        iblUpdate.addActionListener(this::iblUpdateActionPerformed);

        iblSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblSave.setText("Save");
        iblSave.addActionListener(this::iblSaveActionPerformed);

        iblHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        iblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iblHeader.setText("Manage Branch");

        tblBranch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBranch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBranchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBranch);

        iblBranchId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblBranchId.setText("Branch ID");

        iblBranchName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblBranchName.setText("Branch Name");

        iblBranchNametxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblBranchNametxt.addActionListener(this::iblBranchNametxtActionPerformed);

        iblBranchLoca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblBranchLoca.setText("Location");

        iblBranchIdtxt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        iblBranchCode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblBranchCode.setText("Branch Code");

        iblBranchCodetxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblBranchCodetxt.addActionListener(this::iblBranchCodetxtActionPerformed);

        iblDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblDelete.setText("Delete");
        iblDelete.addActionListener(this::iblDeleteActionPerformed);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(iblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iblSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iblContactNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iblContactNotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(iblBranchLoca, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(iblBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(iblBranchCode)
                                    .addComponent(iblBranchId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iblBranchCodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblBranchNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblLocationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblBranchIdtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(394, 394, 394))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iblHeader)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblBranchIdtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblBranchId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(iblBranchCode))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iblBranchCodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblUpdate)
                            .addComponent(iblSave)
                            .addComponent(iblDelete))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iblBranchName)
                            .addComponent(iblBranchNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblLocationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblBranchLoca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblContactNotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblContactNo))
                        .addGap(66, 66, 66)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iblLocationtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblLocationtxtActionPerformed
    }//GEN-LAST:event_iblLocationtxtActionPerformed

    private void iblUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblUpdateActionPerformed
        updateBranch();
    }//GEN-LAST:event_iblUpdateActionPerformed

    private void iblSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblSaveActionPerformed
        saveBranch();
    }//GEN-LAST:event_iblSaveActionPerformed

    private void tblBranchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBranchMouseClicked
        searchBranch();
    }//GEN-LAST:event_tblBranchMouseClicked

    private void iblBranchNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblBranchNametxtActionPerformed
    }//GEN-LAST:event_iblBranchNametxtActionPerformed

    private void iblContactNotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblContactNotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblContactNotxtActionPerformed

    private void iblBranchCodetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblBranchCodetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblBranchCodetxtActionPerformed

    private void iblDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblDeleteActionPerformed
        deleteBranch();
    }//GEN-LAST:event_iblDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            dispose();
            new MainDashboardView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening Branch View : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BranchView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel iblBranchCode;
    private javax.swing.JTextField iblBranchCodetxt;
    private javax.swing.JLabel iblBranchId;
    private javax.swing.JTextField iblBranchIdtxt1;
    private javax.swing.JLabel iblBranchLoca;
    private javax.swing.JLabel iblBranchName;
    private javax.swing.JTextField iblBranchNametxt;
    private javax.swing.JLabel iblContactNo;
    private javax.swing.JTextField iblContactNotxt;
    private javax.swing.JButton iblDelete;
    private javax.swing.JLabel iblHeader;
    private javax.swing.JTextField iblLocationtxt;
    private javax.swing.JButton iblSave;
    private javax.swing.JButton iblUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBranch;
    // End of variables declaration//GEN-END:variables

    public void loadTable() {
        String[] columns = {"Branch ID", "Branch Code", "Branch Name", "Location", "Contact Number"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblBranch.setModel(dtm);

        try {
            List<com.ijse.GearRentPro.dto.BranchDto> branchDtos = branchController.findAllBranches();
            for (com.ijse.GearRentPro.dto.BranchDto branchDto : branchDtos) {
                Object[] rowData = {
                    branchDto.getBranchId(),
                    branchDto.getBranchCode(),
                    branchDto.getName(),
                    branchDto.getAddress(),
                    branchDto.getContactNumber()
                };
                dtm.addRow(rowData);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void saveBranch() {
        BranchDto branchDTO = new BranchDto(
                iblBranchIdtxt1.getText(),
                iblBranchCodetxt.getText(),
                iblBranchNametxt.getText(),
                iblLocationtxt.getText(),
                iblContactNotxt.getText());
        try {
            boolean resp = branchController.saveBranch(branchDTO);
            if (resp) {
                JOptionPane.showMessageDialog(this, "Branch saved successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save branch!");
            }
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void updateBranch() {
        BranchDto branchDTO = new BranchDto(
                iblBranchIdtxt1.getText(),
                iblBranchCodetxt.getText(),
                iblBranchNametxt.getText(),
                iblLocationtxt.getText(),
                iblContactNotxt.getText());
        try {
            boolean resp = branchController.updateBranch(branchDTO);
            if (resp) {
                JOptionPane.showMessageDialog(this, "Branch updated successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update branch!");
            }
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void deleteBranch() {
        String branchId = iblBranchIdtxt1.getText();
        try {
            boolean resp = branchController.deleteBranch(branchId);
            if (resp) {
                JOptionPane.showMessageDialog(this, "Branch deleted successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete branch!");
            }
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void searchBranch() {
        if (tblBranch.getSelectedRow() < 0) {
            return;
        }
        String branchId = (String) tblBranch.getValueAt(tblBranch.getSelectedRow(), 0);

        try {
            com.ijse.GearRentPro.dto.BranchDto branchDto = branchController.findBranch(branchId);
            if (branchDto != null) {
                iblBranchIdtxt1.setText(branchDto.getBranchId());
                iblBranchCodetxt.setText(branchDto.getBranchCode());
                iblBranchNametxt.setText(branchDto.getName());
                iblLocationtxt.setText(branchDto.getAddress());
                iblContactNotxt.setText(branchDto.getContactNumber());
            } else {
                JOptionPane.showMessageDialog(this, "Branch not Found !");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void clearForm() {
        iblBranchIdtxt1.setText("");
        iblBranchCodetxt.setText("");
        iblBranchNametxt.setText("");
        iblLocationtxt.setText("");
        iblContactNotxt.setText("");
    }
}
