
package com.ijse.GearRentPro.view;

import com.ijse.GearRentPro.controller.BranchController;
import com.ijse.GearRentPro.controller.CategoryController;
import com.ijse.GearRentPro.controller.DamageController;
import com.ijse.GearRentPro.controller.EquipmentController;
import com.ijse.GearRentPro.controller.RentalController;
import com.ijse.GearRentPro.dto.BranchDto;
import com.ijse.GearRentPro.dto.CategoryDto;
import com.ijse.GearRentPro.dto.DamageDto;
import com.ijse.GearRentPro.dto.EquipmentDto;
import com.ijse.GearRentPro.dto.RentalDto;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class BranchRevenueReportView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BranchRevenueReportView.class.getName());
    private BranchController branchController = new BranchController();
    private RentalController rentalController = new RentalController();
    private CategoryController categoryController = new CategoryController();
    private DamageController damageController = new DamageController();
    private EquipmentController equipmentController = new EquipmentController();

    /**
     * Creates new form BranchRevenueReportView
     */
    public BranchRevenueReportView() {
        initComponents();
        loadBranches();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblBranch = new javax.swing.JLabel();
        iblTo = new javax.swing.JLabel();
        iblTotxt = new javax.swing.JTextField();
        iblFrom = new javax.swing.JLabel();
        iblFromtxt = new javax.swing.JTextField();
        iblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBranchRevenue = new javax.swing.JTable();
        cmbBranch = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        iblTotalRevenue = new javax.swing.JLabel();
        iblLateFeesTotal = new javax.swing.JLabel();
        iblTotalDamage = new javax.swing.JLabel();
        iblTotalRenals = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iblBranch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblBranch.setText("Branch ");

        iblTo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblTo.setText("To");

        iblTotxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblTotxt.addActionListener(this::iblTotxtActionPerformed);

        iblFrom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblFrom.setText("From");

        iblFromtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblFromtxt.addActionListener(this::iblFromtxtActionPerformed);

        iblHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        iblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iblHeader.setText("Branch Revenue Report");

        tblBranchRevenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBranchRevenue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBranchRevenueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBranchRevenue);

        cmbBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBranch.addActionListener(this::cmbBranchActionPerformed);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnGenerate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(this::btnGenerateActionPerformed);

        iblTotalRevenue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblTotalRevenue.setText("Total Revenue  :  ");
        iblTotalRevenue.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        iblLateFeesTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblLateFeesTotal.setText("Total Late Fees : ");
        iblLateFeesTotal.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        iblTotalDamage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblTotalDamage.setText("Total Damage  : ");
        iblTotalDamage.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        iblTotalRenals.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblTotalRenals.setText("Total Rentals    :");
        iblTotalRenals.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iblTotalRenals, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblLateFeesTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblTotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblTotalDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(234, 234, 234)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(iblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbBranch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblFromtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblTotxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iblHeader)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iblBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblFrom)
                    .addComponent(iblFromtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iblTo)
                    .addComponent(iblTotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGenerate)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(iblTotalRenals, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iblLateFeesTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iblTotalRevenue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iblTotalDamage)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iblTotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblTotxtActionPerformed

    }//GEN-LAST:event_iblTotxtActionPerformed

    private void iblFromtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblFromtxtActionPerformed

    }//GEN-LAST:event_iblFromtxtActionPerformed

    private void tblBranchRevenueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBranchRevenueMouseClicked

    }//GEN-LAST:event_tblBranchRevenueMouseClicked

    private void cmbBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBranchActionPerformed

    }//GEN-LAST:event_cmbBranchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            dispose();
            new MainDashboardView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening Branch Revenue Report: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        generateReport();
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void loadBranches() {
        try {
            cmbBranch.removeAllItems();
            cmbBranch.addItem("All Branches");
            List<BranchDto> branches = branchController.findAllBranches();
            for (BranchDto branch : branches) {
                cmbBranch.addItem(branch.getBranchId() + " - " + branch.getName());
            }
        } catch (Exception e) {}
    }

    private void generateReport() {
        try {
            String selectedBranch = (String) cmbBranch.getSelectedItem();
            String startDateStr = iblFromtxt.getText().trim();
            String endDateStr = iblTotxt.getText().trim();

            if (startDateStr.isBlank() || endDateStr.isBlank()) {
                JOptionPane.showMessageDialog(this, "From and To dates are required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            LocalDate startDate = LocalDate.parse(startDateStr);
            LocalDate endDate = LocalDate.parse(endDateStr);

            if (startDate.isAfter(endDate)) {
                JOptionPane.showMessageDialog(this, "From date cannot be after To date.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Rental ID", "Customer ID", "Equipment ID", "Start Date", "End Date", "Amount", "Late Fee", "Damage", "Total"}, 0
            ) {
                public boolean isCellEditable(int row, int column) { return false; }
            };
            tblBranchRevenue.setModel(model);

            List<RentalDto> rentals = rentalController.findAllRentals();

            int totalRentals = 0;
            double totalRevenue = 0, totalLateFees = 0, totalDamage = 0;

            for (RentalDto rental : rentals) {
                if (rental.getStartDate() == null) continue;
                if (rental.getStartDate().isBefore(startDate) || rental.getStartDate().isAfter(endDate)) continue;
                if (!"All Branches".equals(selectedBranch) && !selectedBranch.startsWith(rental.getBranchId())) continue;

                double amount = rental.getRentalAmount();
                double lateFee = 0;
                if (rental.getActualReturnDate() != null && rental.getEndDate() != null && rental.getActualReturnDate().isAfter(rental.getEndDate())) {
                    long lateDays = ChronoUnit.DAYS.between(rental.getEndDate(), rental.getActualReturnDate());
                    try {
                        EquipmentDto equipment = equipmentController.findEquipment(rental.getEquipmentId());
                        if (equipment != null) {
                            CategoryDto category = categoryController.findCategory(equipment.getCategoryId());
                            lateFee = lateDays * category.getLateFeePerDay();
                        }
                    } catch (Exception ignored) {
                    }
                }

                double damage = 0;
                try {
                    List<DamageDto> damages = damageController.findDamagesByRentalId(rental.getRentalId());
                    for (DamageDto damageDto : damages) {
                        damage += damageDto.getDamageCharge();
                    }
                } catch (Exception ignored) {
                }
                double total = amount + lateFee + damage;

                model.addRow(new Object[]{
                    rental.getRentalId(), rental.getCustomerId(), rental.getEquipmentId(),
                    rental.getStartDate(), rental.getEndDate(),
                    amount, lateFee, damage, total
                });

                totalRentals++;
                totalRevenue += amount;
                totalLateFees += lateFee;
                totalDamage += damage;
            }

            iblTotalRenals.setText("Total Rentals : " + totalRentals);
            iblTotalRevenue.setText("Total Revenue : LKR " + totalRevenue);
            iblLateFeesTotal.setText("Total Late Fees : LKR " + totalLateFees);
            iblTotalDamage.setText("Total Damage : LKR " + totalDamage);

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Please use YYYY-MM-DD for From and To dates.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BranchRevenueReportView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JComboBox<String> cmbBranch;
    private javax.swing.JLabel iblBranch;
    private javax.swing.JLabel iblFrom;
    private javax.swing.JTextField iblFromtxt;
    private javax.swing.JLabel iblHeader;
    private javax.swing.JLabel iblLateFeesTotal;
    private javax.swing.JLabel iblTo;
    private javax.swing.JLabel iblTotalDamage;
    private javax.swing.JLabel iblTotalRenals;
    private javax.swing.JLabel iblTotalRevenue;
    private javax.swing.JTextField iblTotxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBranchRevenue;
    // End of variables declaration//GEN-END:variables
}