/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ijse.GearRentPro.view;

import com.ijse.GearRentPro.controller.CategoryController;
import com.ijse.GearRentPro.dto.CategoryDto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CategoryView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CategoryView.class.getName());
    private CategoryController categoryController = new CategoryController();

    /**
     * Creates new form CategoryView
     */
    public CategoryView() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblDelete = new javax.swing.JButton();
        iblCatId = new javax.swing.JLabel();
        iblCatDes = new javax.swing.JLabel();
        iblCatPricefactortxt = new javax.swing.JTextField();
        iblCatDestxt = new javax.swing.JTextField();
        iblCatWM = new javax.swing.JLabel();
        iblCatPricefactor = new javax.swing.JLabel();
        iblCatWMtxt = new javax.swing.JTextField();
        iblCatIdtxt = new javax.swing.JTextField();
        iblUpdate = new javax.swing.JButton();
        iblCatName = new javax.swing.JLabel();
        iblCatNametxt = new javax.swing.JTextField();
        iblSave = new javax.swing.JButton();
        iblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategory = new javax.swing.JTable();
        iblCatIsActive = new javax.swing.JLabel();
        iblCatLateFeeperday = new javax.swing.JLabel();
        iblCatIsActivetxt = new javax.swing.JTextField();
        iblCatLateFeeperdaytxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iblDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblDelete.setText("Delete");
        iblDelete.addActionListener(this::iblDeleteActionPerformed);

        iblCatId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCatId.setText("Category ID");

        iblCatDes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCatDes.setText("Description");

        iblCatPricefactortxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblCatPricefactortxt.addActionListener(this::iblCatPricefactortxtActionPerformed);

        iblCatDestxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblCatDestxt.addActionListener(this::iblCatDestxtActionPerformed);

        iblCatWM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCatWM.setText("Weekend Multiplier");

        iblCatPricefactor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCatPricefactor.setText("Price Factor");

        iblCatWMtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblCatWMtxt.addActionListener(this::iblCatWMtxtActionPerformed);

        iblCatIdtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        iblUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblUpdate.setText("Update");
        iblUpdate.addActionListener(this::iblUpdateActionPerformed);

        iblCatName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCatName.setText("Category Name");

        iblCatNametxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblCatNametxt.addActionListener(this::iblCatNametxtActionPerformed);

        iblSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblSave.setText("Save");
        iblSave.addActionListener(this::iblSaveActionPerformed);

        iblHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        iblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iblHeader.setText("Manage Category");

        tblCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCategory);

        iblCatIsActive.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCatIsActive.setText("Is Active");

        iblCatLateFeeperday.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCatLateFeeperday.setText("Late Fee Per Day");

        iblCatIsActivetxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblCatIsActivetxt.addActionListener(this::iblCatIsActivetxtActionPerformed);

        iblCatLateFeeperdaytxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblCatLateFeeperdaytxt.addActionListener(this::iblCatLateFeeperdaytxtActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(251, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iblCatNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblCatDestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblCatPricefactortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iblCatId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iblCatIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iblCatLateFeeperday)
                                    .addComponent(iblCatWM)
                                    .addComponent(iblCatIsActive, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblCatPricefactor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblCatDes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblCatName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(iblCatWMtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(iblCatLateFeeperdaytxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(iblCatIsActivetxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(438, 438, 438))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iblSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iblHeader)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iblCatIdtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblCatId, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblCatNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblCatName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblSave)
                            .addComponent(iblUpdate)
                            .addComponent(iblDelete))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblCatDestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblCatDes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblCatPricefactortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblCatPricefactor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblCatWMtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblCatWM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblCatLateFeeperdaytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblCatLateFeeperday, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblCatIsActivetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblCatIsActive, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iblDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblDeleteActionPerformed
        deleteCategory();
    }//GEN-LAST:event_iblDeleteActionPerformed

    private void iblCatPricefactortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblCatPricefactortxtActionPerformed

    }//GEN-LAST:event_iblCatPricefactortxtActionPerformed

    private void iblCatDestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblCatDestxtActionPerformed

    }//GEN-LAST:event_iblCatDestxtActionPerformed

    private void iblCatWMtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblCatWMtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblCatWMtxtActionPerformed

    private void iblUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblUpdateActionPerformed
        updateCategory();
    }//GEN-LAST:event_iblUpdateActionPerformed

    private void iblCatNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblCatNametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblCatNametxtActionPerformed

    private void iblSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblSaveActionPerformed
        saveCategory();
    }//GEN-LAST:event_iblSaveActionPerformed

    private void tblCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoryMouseClicked
        searchCategory();
    }//GEN-LAST:event_tblCategoryMouseClicked

    private void iblCatIsActivetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblCatIsActivetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblCatIsActivetxtActionPerformed

    private void iblCatLateFeeperdaytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblCatLateFeeperdaytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblCatLateFeeperdaytxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CategoryView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iblCatDes;
    private javax.swing.JTextField iblCatDestxt;
    private javax.swing.JLabel iblCatId;
    private javax.swing.JTextField iblCatIdtxt;
    private javax.swing.JLabel iblCatIsActive;
    private javax.swing.JTextField iblCatIsActivetxt;
    private javax.swing.JLabel iblCatLateFeeperday;
    private javax.swing.JTextField iblCatLateFeeperdaytxt;
    private javax.swing.JLabel iblCatName;
    private javax.swing.JTextField iblCatNametxt;
    private javax.swing.JLabel iblCatPricefactor;
    private javax.swing.JTextField iblCatPricefactortxt;
    private javax.swing.JLabel iblCatWM;
    private javax.swing.JTextField iblCatWMtxt;
    private javax.swing.JButton iblDelete;
    private javax.swing.JLabel iblHeader;
    private javax.swing.JButton iblSave;
    private javax.swing.JButton iblUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCategory;
    // End of variables declaration//GEN-END:variables

    public void loadTable() {
        String[] columns = {"Category ID", "Name", "Description", "Price Factor", "Weekend Multiplier", "Late Fee Per Day", "Is Active"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblCategory.setModel(dtm);

        try {
            List<CategoryDto> categoryDtos = categoryController.findAllCategories();
            for (CategoryDto dto : categoryDtos) {
                Object[] rowData = {
                    dto.getCategoryId(),
                    dto.getName(),
                    dto.getDescription(),
                    dto.getPriceFactor(),
                    dto.getWeekendMutiplier(),
                    dto.getLateFeePerDay(),
                    dto.isIsActive()
                };
                dtm.addRow(rowData);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void saveCategory() {
        CategoryDto dto = new CategoryDto(
                iblCatIdtxt.getText(),
                iblCatNametxt.getText(),
                iblCatDestxt.getText(),
                Double.parseDouble(iblCatPricefactortxt.getText()),
                Double.parseDouble(iblCatWMtxt.getText()),
                Double.parseDouble(iblCatLateFeeperdaytxt.getText()),
                Boolean.parseBoolean(iblCatIsActivetxt.getText())
        );

        try {
            boolean resp = categoryController.saveCategory(dto);
            if (resp) {
                JOptionPane.showMessageDialog(this, "Category saved successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save category!");
            }
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void updateCategory() {
        CategoryDto dto = new CategoryDto(
                iblCatIdtxt.getText(),
                iblCatNametxt.getText(),
                iblCatDestxt.getText(),
                Double.parseDouble(iblCatPricefactortxt.getText()),
                Double.parseDouble(iblCatWMtxt.getText()),
                Double.parseDouble(iblCatLateFeeperdaytxt.getText()),
                Boolean.parseBoolean(iblCatIsActivetxt.getText())
        );

        try {
            boolean resp = categoryController.updateCategory(dto);
            if (resp) {
                JOptionPane.showMessageDialog(this, "Category updated successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update category!");
            }
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void deleteCategory() {
        String categoryId = iblCatIdtxt.getText();
        try {
            boolean resp = categoryController.deleteCategory(categoryId);
            if (resp) {
                JOptionPane.showMessageDialog(this, "Category deleted successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete category!");
            }
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void searchCategory() {
        if (tblCategory.getSelectedRow() < 0) {
            return;
        }

        String categoryId = (String) tblCategory.getValueAt(tblCategory.getSelectedRow(), 0);
        try {
            CategoryDto dto = categoryController.findCategory(categoryId);
            if (dto != null) {
                iblCatIdtxt.setText(dto.getCategoryId());
                iblCatNametxt.setText(dto.getName());
                iblCatDestxt.setText(dto.getDescription());
                iblCatPricefactortxt.setText(String.valueOf(dto.getPriceFactor()));
                iblCatWMtxt.setText(String.valueOf(dto.getWeekendMutiplier()));
                iblCatLateFeeperdaytxt.setText(String.valueOf(dto.getLateFeePerDay()));
                iblCatIsActivetxt.setText(String.valueOf(dto.isIsActive()));
            } else {
                JOptionPane.showMessageDialog(this, "Category not Found !");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void clearForm() {
        iblCatIdtxt.setText("");
        iblCatNametxt.setText("");
        iblCatDestxt.setText("");
        iblCatPricefactortxt.setText("");
        iblCatWMtxt.setText("");
        iblCatLateFeeperdaytxt.setText("");
        iblCatIsActivetxt.setText("");
    }
}
