/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ijse.GearRentPro.view;

import com.ijse.GearRentPro.controller.CustomerController;
import com.ijse.GearRentPro.controller.MembershipController;
import com.ijse.GearRentPro.dto.CustomerDto;
import com.ijse.GearRentPro.dto.MembershipDto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CustomerView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerView.class.getName());
    private CustomerController customerController = new CustomerController();
    private MembershipController membershipController = new MembershipController();

    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
        initComponents();
        loadMemberships();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblCustNametxt = new javax.swing.JTextField();
        iblCustomerId = new javax.swing.JLabel();
        iblSave = new javax.swing.JButton();
        iblNICOrPassport = new javax.swing.JLabel();
        iblHeader = new javax.swing.JLabel();
        iblCustContactNotxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        iblNICOrPassporttxt = new javax.swing.JTextField();
        iblCustEmail = new javax.swing.JLabel();
        iblCustMembershipId = new javax.swing.JLabel();
        iblCustContactNo = new javax.swing.JLabel();
        iblCustAddress = new javax.swing.JLabel();
        iblCustEmailtxt = new javax.swing.JTextField();
        iblCustomerIdtxt = new javax.swing.JTextField();
        iblCustAddresstxt = new javax.swing.JTextField();
        iblUpdate = new javax.swing.JButton();
        iblCustName = new javax.swing.JLabel();
        iblDelete = new javax.swing.JButton();
        cmbMembershipId = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iblCustNametxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblCustNametxt.addActionListener(this::iblCustNametxtActionPerformed);

        iblCustomerId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCustomerId.setText("Customer ID");

        iblSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblSave.setText("Save");
        iblSave.addActionListener(this::iblSaveActionPerformed);

        iblNICOrPassport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblNICOrPassport.setText("NIC/Passport");

        iblHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        iblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iblHeader.setText("Manage Customer");

        iblCustContactNotxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblCustContactNotxt.addActionListener(this::iblCustContactNotxtActionPerformed);

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        iblNICOrPassporttxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblNICOrPassporttxt.addActionListener(this::iblNICOrPassporttxtActionPerformed);

        iblCustEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCustEmail.setText("Email");

        iblCustMembershipId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCustMembershipId.setText("Membership ID");

        iblCustContactNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCustContactNo.setText("Contact Number");

        iblCustAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCustAddress.setText("Address");

        iblCustEmailtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblCustEmailtxt.addActionListener(this::iblCustEmailtxtActionPerformed);

        iblCustomerIdtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        iblCustAddresstxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblCustAddresstxt.addActionListener(this::iblCustAddresstxtActionPerformed);

        iblUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblUpdate.setText("Update");
        iblUpdate.addActionListener(this::iblUpdateActionPerformed);

        iblCustName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCustName.setText("Customer Name");

        iblDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblDelete.setText("Delete");
        iblDelete.addActionListener(this::iblDeleteActionPerformed);

        cmbMembershipId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iblCustNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblNICOrPassporttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblCustContactNotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iblCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(iblCustomerIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iblCustAddress)
                                    .addComponent(iblCustEmail)
                                    .addComponent(iblCustMembershipId, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblCustContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblNICOrPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblCustName))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(iblCustEmailtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(iblCustAddresstxt, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(cmbMembershipId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(438, 438, 438))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(iblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iblSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iblHeader)
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iblCustomerIdtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblCustomerId, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblCustNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblCustName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblSave)
                            .addComponent(iblUpdate)
                            .addComponent(iblDelete))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblNICOrPassporttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblNICOrPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblCustContactNotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblCustContactNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblCustEmailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblCustEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblCustAddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblCustAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbMembershipId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblCustMembershipId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iblCustNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblCustNametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblCustNametxtActionPerformed

    private void iblSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblSaveActionPerformed
        saveCustomer();
    }//GEN-LAST:event_iblSaveActionPerformed

    private void iblCustContactNotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblCustContactNotxtActionPerformed

    }//GEN-LAST:event_iblCustContactNotxtActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        searchCustomer();
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void iblNICOrPassporttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblNICOrPassporttxtActionPerformed

    }//GEN-LAST:event_iblNICOrPassporttxtActionPerformed

    private void iblCustEmailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblCustEmailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblCustEmailtxtActionPerformed

    private void iblCustAddresstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblCustAddresstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblCustAddresstxtActionPerformed

    private void iblUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblUpdateActionPerformed
        updateCustomer();
    }//GEN-LAST:event_iblUpdateActionPerformed

    private void iblDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblDeleteActionPerformed
        deleteCustomer();
    }//GEN-LAST:event_iblDeleteActionPerformed

    private void loadMemberships() {
        try {
            cmbMembershipId.removeAllItems();
            List<MembershipDto> memberships = membershipController.findAllMemberships();
            for (MembershipDto membership : memberships) {
                cmbMembershipId.addItem(membership.getMembershipId() + " - " + membership.getLevel());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading memberships: " + e.getMessage());
        }
    }

    private void loadTable() {
        try {
            DefaultTableModel model = new DefaultTableModel(
                    new Object[]{"Customer ID", "Name", "NIC/Passport", "Contact No", "Email", "Address", "Membership ID"},
                    0
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            tblCustomer.setModel(model);

            List<CustomerDto> customers = customerController.findAllCustomers();
            for (CustomerDto customer : customers) {
                model.addRow(new Object[]{
                    customer.getCustomerId(),
                    customer.getName(),
                    customer.getNicOrPassport(),
                    customer.getContactNo(),
                    customer.getEmail(),
                    customer.getAddress(),
                    customer.getMembershipId()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading customers: " + e.getMessage());
        }
    }

    private void saveCustomer() {
        try {
            String membershipId = cmbMembershipId.getSelectedItem().toString().split(" - ")[0];
            CustomerDto dto = new CustomerDto(
                    iblCustomerIdtxt.getText(),
                    iblCustNametxt.getText(),
                    iblNICOrPassporttxt.getText(),
                    iblCustContactNotxt.getText(),
                    iblCustEmailtxt.getText(),
                    iblCustAddresstxt.getText(),
                    membershipId
            );

            boolean isSaved = customerController.saveCustomer(dto);
            if (isSaved) {
                JOptionPane.showMessageDialog(this, "Customer saved successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save customer.");
            }
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving customer: " + e.getMessage());
        }
    }

    private void updateCustomer() {
        try {
            String membershipId = cmbMembershipId.getSelectedItem().toString().split(" - ")[0];
            CustomerDto dto = new CustomerDto(
                    iblCustomerIdtxt.getText(),
                    iblCustNametxt.getText(),
                    iblNICOrPassporttxt.getText(),
                    iblCustContactNotxt.getText(),
                    iblCustEmailtxt.getText(),
                    iblCustAddresstxt.getText(),
                    membershipId
            );

            boolean isUpdated = customerController.updateCustomer(dto);
            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Customer updated successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update customer.");
            }
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating customer: " + e.getMessage());
        }
    }

    private void deleteCustomer() {
        try {
            String id = iblCustomerIdtxt.getText();
            boolean isDeleted = customerController.deleteCustomer(id);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Customer deleted successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete customer.");
            }
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error deleting customer: " + e.getMessage());
        }
    }

    private void searchCustomer() {
        try {
            int selectedRow = tblCustomer.getSelectedRow();
            if (selectedRow < 0) {
                return;
            }

            String id = tblCustomer.getValueAt(selectedRow, 0).toString();
            CustomerDto dto = customerController.findCustomer(id);

            if (dto == null) {
                JOptionPane.showMessageDialog(this, "Customer not found.");
                return;
            }

            iblCustomerIdtxt.setText(dto.getCustomerId());
            iblCustNametxt.setText(dto.getName());
            iblNICOrPassporttxt.setText(dto.getNicOrPassport());
            iblCustContactNotxt.setText(dto.getContactNo());
            iblCustEmailtxt.setText(dto.getEmail());
            iblCustAddresstxt.setText(dto.getAddress());

            for (int i = 0; i < cmbMembershipId.getItemCount(); i++) {
                String item = cmbMembershipId.getItemAt(i);
                if (item.startsWith(dto.getMembershipId() + " - ")) {
                    cmbMembershipId.setSelectedIndex(i);
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error searching customer: " + e.getMessage());
        }
    }

    private void clearForm() {
        iblCustomerIdtxt.setText("");
        iblCustNametxt.setText("");
        iblNICOrPassporttxt.setText("");
        iblCustContactNotxt.setText("");
        iblCustEmailtxt.setText("");
        iblCustAddresstxt.setText("");
        if (cmbMembershipId.getItemCount() > 0) {
            cmbMembershipId.setSelectedIndex(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbMembershipId;
    private javax.swing.JLabel iblCustAddress;
    private javax.swing.JTextField iblCustAddresstxt;
    private javax.swing.JLabel iblCustContactNo;
    private javax.swing.JTextField iblCustContactNotxt;
    private javax.swing.JLabel iblCustEmail;
    private javax.swing.JTextField iblCustEmailtxt;
    private javax.swing.JLabel iblCustMembershipId;
    private javax.swing.JLabel iblCustName;
    private javax.swing.JTextField iblCustNametxt;
    private javax.swing.JLabel iblCustomerId;
    private javax.swing.JTextField iblCustomerIdtxt;
    private javax.swing.JButton iblDelete;
    private javax.swing.JLabel iblHeader;
    private javax.swing.JLabel iblNICOrPassport;
    private javax.swing.JTextField iblNICOrPassporttxt;
    private javax.swing.JButton iblSave;
    private javax.swing.JButton iblUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomer;
    // End of variables declaration//GEN-END:variables
}
