/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ijse.GearRentPro.view;

import com.ijse.GearRentPro.controller.EquipmentController;
import com.ijse.GearRentPro.dto.EquipmentDto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class EquipmentView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EquipmentView.class.getName());

    private EquipmentController equipmentController = new EquipmentController();

    /**
     * Creates new form equipmentView
     */
    public EquipmentView() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblHeader = new javax.swing.JLabel();
        iblEquiId = new javax.swing.JLabel();
        iblEquiIdtxt = new javax.swing.JTextField();
        iblCateiId1 = new javax.swing.JLabel();
        iblCateIdtxt = new javax.swing.JTextField();
        iblBranchId = new javax.swing.JLabel();
        iblBranchIdtxt = new javax.swing.JTextField();
        iblBrand = new javax.swing.JLabel();
        iblBrandtxt = new javax.swing.JTextField();
        iblModel = new javax.swing.JLabel();
        iblModeltxt = new javax.swing.JTextField();
        iblPurchaseYear = new javax.swing.JLabel();
        iblDepositAmountTxt = new javax.swing.JTextField();
        iblDepositAmount = new javax.swing.JLabel();
        iblPurchaseYeartxt = new javax.swing.JTextField();
        iblBaseDailyPricetxt = new javax.swing.JTextField();
        iblBaseDailyPrice = new javax.swing.JLabel();
        iblStatustxt = new javax.swing.JTextField();
        iblStatus = new javax.swing.JLabel();
        iblUpdate = new javax.swing.JButton();
        iblDelete = new javax.swing.JButton();
        iblSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblequipment = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iblHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        iblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iblHeader.setText("Manage Equipment");

        iblEquiId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblEquiId.setText("Equipment ID");

        iblEquiIdtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblEquiIdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iblEquiIdtxtActionPerformed(evt);
            }
        });

        iblCateiId1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCateiId1.setText("Category ID");

        iblCateIdtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        iblBranchId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblBranchId.setText("Branch ID");

        iblBranchIdtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblBranchIdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iblBranchIdtxtActionPerformed(evt);
            }
        });

        iblBrand.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblBrand.setText("Brand");

        iblBrandtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        iblModel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblModel.setText("Model");

        iblModeltxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblModeltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iblModeltxtActionPerformed(evt);
            }
        });

        iblPurchaseYear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblPurchaseYear.setText("Purchase Year");

        iblDepositAmountTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblDepositAmountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iblDepositAmountTxtActionPerformed(evt);
            }
        });

        iblDepositAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblDepositAmount.setText("Deposit Amount");

        iblPurchaseYeartxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        iblBaseDailyPricetxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        iblBaseDailyPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblBaseDailyPrice.setText("Base Daily Price");

        iblStatustxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        iblStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblStatus.setText("Status");

        iblUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblUpdate.setText("Update");
        iblUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iblUpdateActionPerformed(evt);
            }
        });

        iblDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblDelete.setText("Delete");
        iblDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iblDeleteActionPerformed(evt);
            }
        });

        iblSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblSave.setText("Save");
        iblSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iblSaveActionPerformed(evt);
            }
        });

        tblequipment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblequipment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblequipmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblequipment);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(iblModel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(iblEquiId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                        .addComponent(iblCateiId1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(iblBranchId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(iblBrand, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(iblPurchaseYear))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(iblBrandtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(iblModeltxt)
                                    .addComponent(iblEquiIdtxt)
                                    .addComponent(iblCateIdtxt)
                                    .addComponent(iblBranchIdtxt)
                                    .addComponent(iblPurchaseYeartxt))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(iblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(iblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(iblSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(iblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(iblDepositAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(iblBaseDailyPrice))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(iblBaseDailyPricetxt)
                                            .addComponent(iblDepositAmountTxt)
                                            .addComponent(iblStatustxt))))))))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblEquiId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblEquiIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iblCateiId1)
                    .addComponent(iblCateIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblBranchId)
                    .addComponent(iblBranchIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iblBrand)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(iblBaseDailyPrice)
                        .addComponent(iblBaseDailyPricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(iblBrandtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblDepositAmount)
                            .addComponent(iblDepositAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblStatus)
                            .addComponent(iblStatustxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblUpdate)
                            .addComponent(iblDelete)
                            .addComponent(iblSave)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblModel)
                            .addComponent(iblModeltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iblPurchaseYear)
                            .addComponent(iblPurchaseYeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iblEquiIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblEquiIdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblEquiIdtxtActionPerformed

    private void iblBranchIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblBranchIdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblBranchIdtxtActionPerformed

    private void iblModeltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblModeltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblModeltxtActionPerformed

    private void iblUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblUpdateActionPerformed
        updateEquipment();
    }//GEN-LAST:event_iblUpdateActionPerformed

    private void iblSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblSaveActionPerformed
        saveEquipment();
    }//GEN-LAST:event_iblSaveActionPerformed

    private void iblDepositAmountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblDepositAmountTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblDepositAmountTxtActionPerformed

    private void tblequipmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblequipmentMouseClicked
        searchEquipment();
    }//GEN-LAST:event_tblequipmentMouseClicked

    private void iblDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblDeleteActionPerformed
        deleteEquipment();
    }//GEN-LAST:event_iblDeleteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iblBaseDailyPrice;
    private javax.swing.JTextField iblBaseDailyPricetxt;
    private javax.swing.JLabel iblBranchId;
    private javax.swing.JTextField iblBranchIdtxt;
    private javax.swing.JLabel iblBrand;
    private javax.swing.JTextField iblBrandtxt;
    private javax.swing.JTextField iblCateIdtxt;
    private javax.swing.JLabel iblCateiId1;
    private javax.swing.JButton iblDelete;
    private javax.swing.JLabel iblDepositAmount;
    private javax.swing.JTextField iblDepositAmountTxt;
    private javax.swing.JLabel iblEquiId;
    private javax.swing.JTextField iblEquiIdtxt;
    private javax.swing.JLabel iblHeader;
    private javax.swing.JLabel iblModel;
    private javax.swing.JTextField iblModeltxt;
    private javax.swing.JLabel iblPurchaseYear;
    private javax.swing.JTextField iblPurchaseYeartxt;
    private javax.swing.JButton iblSave;
    private javax.swing.JLabel iblStatus;
    private javax.swing.JTextField iblStatustxt;
    private javax.swing.JButton iblUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblequipment;
    // End of variables declaration//GEN-END:variables

    public void loadTable() {
        String columns[] = {"Equipment ID", "Category ID", "Branch ID", "Brand", "Model", "Purchase Year", "Base Daily Price", "Security Deposit", "Status"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        tblequipment.setModel(dtm);

        try {
            List<EquipmentDto> equipmentDtos = equipmentController.findAllEquipments();
            for (EquipmentDto equipmentDto : equipmentDtos) {
                Object[] rowData = {equipmentDto.getEquipmentId(), equipmentDto.getCategoryId(), equipmentDto.getBranchId(), equipmentDto.getBrand(), equipmentDto.getModel(), equipmentDto.getPurchaseYear(), equipmentDto.getBaseDailyPrice(), equipmentDto.getSecurityDeposit(), equipmentDto.getStatus()};

                dtm.addRow(rowData);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void saveEquipment() {

        EquipmentDto equipmentDto = new EquipmentDto(iblEquiIdtxt.getText(), iblCateIdtxt.getText(), iblBranchIdtxt.getText(), iblBrandtxt.getText(),
                iblModeltxt.getText(), Integer.parseInt(iblPurchaseYeartxt.getText()),
                Double.parseDouble(iblBaseDailyPricetxt.getText()), Double.parseDouble(iblDepositAmountTxt.getText()),
                iblStatustxt.getText());
        try {
            boolean resp = equipmentController.saveEquipment(equipmentDto);

            if (resp) {
                JOptionPane.showMessageDialog(this, "Equipment saved successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save equipment!");
            }

            loadTable();
            clearForm();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }

    public void clearForm() {
        iblEquiIdtxt.setText("");
        iblCateIdtxt.setText("");
        iblBranchIdtxt.setText("");
        iblBrandtxt.setText("");
        iblModeltxt.setText("");
        iblPurchaseYeartxt.setText("");
        iblBaseDailyPricetxt.setText("");
        iblDepositAmountTxt.setText("");
        iblStatustxt.setText("");

    }

    public void searchEquipment() {
        String equipmentId = (String) tblequipment.getValueAt(tblequipment.getSelectedRow(), 0);

        try {
            EquipmentDto equipmentDto = equipmentController.findEquipment(equipmentId);
            if (equipmentDto != null) {
                iblEquiIdtxt.setText(equipmentDto.getEquipmentId());
                iblCateIdtxt.setText(equipmentDto.getCategoryId());
                iblBranchIdtxt.setText(equipmentDto.getBranchId());
                iblBrandtxt.setText(equipmentDto.getBrand());
                iblModeltxt.setText(equipmentDto.getModel());
                iblPurchaseYeartxt.setText(Integer.toString(equipmentDto.getPurchaseYear()));
                iblBaseDailyPricetxt.setText(Double.toString(equipmentDto.getBaseDailyPrice()));
                iblDepositAmountTxt.setText(Double.toString(equipmentDto.getSecurityDeposit()));
                iblStatustxt.setText(equipmentDto.getStatus());
            } else {
                JOptionPane.showMessageDialog(this, "Equipment not Found !");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }

    public void updateEquipment() {
        EquipmentDto equipmentDto = new EquipmentDto(
                iblEquiIdtxt.getText(),
                iblCateIdtxt.getText(),
                iblBranchIdtxt.getText(),
                iblBrandtxt.getText(),
                iblModeltxt.getText(),
                Integer.parseInt(iblPurchaseYeartxt.getText()),
                Double.parseDouble(iblBaseDailyPricetxt.getText()),
                Double.parseDouble(iblDepositAmountTxt.getText()),
                iblStatustxt.getText());
        try {
            boolean resp = equipmentController.updateEquipment(equipmentDto);
            if (resp) {
                JOptionPane.showMessageDialog(this, "Equipment updated successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update equipment!");
            }
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void deleteEquipment() {
        String equipmentId = iblEquiIdtxt.getText();
        try {
            boolean resp = equipmentController.deleteEquipment(equipmentId);
            if (resp) {
                JOptionPane.showMessageDialog(this, "Equipment deleted successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete equipment!");
            }
            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
}
