
package com.ijse.GearRentPro.view;

import com.ijse.GearRentPro.controller.BranchController;
import com.ijse.GearRentPro.controller.EquipmentController;
import com.ijse.GearRentPro.controller.RentalController;
import com.ijse.GearRentPro.dto.BranchDto;
import com.ijse.GearRentPro.dto.EquipmentDto;
import com.ijse.GearRentPro.dto.RentalDto;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class EquipmentUtilizationsReport extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EquipmentUtilizationsReport.class.getName());
    private BranchController branchController = new BranchController();
    private RentalController rentalController = new RentalController();
    private EquipmentController equipmentController = new EquipmentController();

    /**
     * Creates new form Report
     */
    public EquipmentUtilizationsReport() {
        initComponents();
        loadBranches();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblequipmentzutilization = new javax.swing.JTable();
        cmbBranch = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        iblMostUtilization = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JButton();
        iblTotxt = new javax.swing.JTextField();
        iblBranch = new javax.swing.JLabel();
        iblLeastUtilized = new javax.swing.JLabel();
        iblAvgUtilization = new javax.swing.JLabel();
        iblFrom = new javax.swing.JLabel();
        iblTo = new javax.swing.JLabel();
        iblTotalEquipments = new javax.swing.JLabel();
        iblFromtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iblHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        iblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iblHeader.setText("Equipment Utilization Report");

        tblequipmentzutilization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblequipmentzutilization.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblequipmentzutilizationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblequipmentzutilization);

        cmbBranch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBranch.addActionListener(this::cmbBranchActionPerformed);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        iblMostUtilization.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblMostUtilization.setText("Most Utilized      : ");
        iblMostUtilization.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnGenerate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(this::btnGenerateActionPerformed);

        iblTotxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblTotxt.addActionListener(this::iblTotxtActionPerformed);

        iblBranch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblBranch.setText("Branch ");

        iblLeastUtilized.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblLeastUtilized.setText("Least Utilized      : ");
        iblLeastUtilized.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        iblAvgUtilization.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblAvgUtilization.setText("Avg Utilization   :  ");
        iblAvgUtilization.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        iblFrom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblFrom.setText("From    ");

        iblTo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblTo.setText("To         ");

        iblTotalEquipments.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblTotalEquipments.setText("Total Equipment :");
        iblTotalEquipments.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        iblFromtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblFromtxt.addActionListener(this::iblFromtxtActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iblLeastUtilized, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblMostUtilization, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblAvgUtilization, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(iblBranch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblTo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblFromtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblTotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(iblTotalEquipments, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iblHeader)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblFrom)
                    .addComponent(iblFromtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblTo)
                    .addComponent(iblTotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGenerate)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(iblTotalEquipments, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iblMostUtilization, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iblAvgUtilization, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iblLeastUtilized)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblequipmentzutilizationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblequipmentzutilizationMouseClicked

    }//GEN-LAST:event_tblequipmentzutilizationMouseClicked

    private void cmbBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBranchActionPerformed

    }//GEN-LAST:event_cmbBranchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            dispose();
            new MainDashboardView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening Equipment Utilization Report : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        generateReport();
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void iblTotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblTotxtActionPerformed

    }//GEN-LAST:event_iblTotxtActionPerformed

    private void iblFromtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblFromtxtActionPerformed

    }//GEN-LAST:event_iblFromtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    private void loadBranches() {
        try {
            cmbBranch.removeAllItems();
            cmbBranch.addItem("All Branches");
            List<BranchDto> branches = branchController.findAllBranches();
            for (BranchDto branch : branches) {
                cmbBranch.addItem(branch.getBranchId() + " - " + branch.getName());
            }
        } catch (Exception e) {}
    }

    private void generateReport() {
        try {
            String selectedBranch = (String) cmbBranch.getSelectedItem();
            String startDateStr = iblFromtxt.getText().trim();
            String endDateStr = iblTotxt.getText().trim();

            if (startDateStr.isBlank() || endDateStr.isBlank()) {
                JOptionPane.showMessageDialog(this, "From and To dates are required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            LocalDate startDate = LocalDate.parse(startDateStr);
            LocalDate endDate = LocalDate.parse(endDateStr);

            if (startDate.isAfter(endDate)) {
                JOptionPane.showMessageDialog(this, "From date cannot be after To date.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            long totalDays = ChronoUnit.DAYS.between(startDate, endDate) + 1;

            DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Equipment ID", "Brand", "Model", "Category", "Total Days", "Days Rented", "Days Available", "Utilization %"}, 0
            ) {
                public boolean isCellEditable(int row, int column) { return false; }
            };
            tblequipmentzutilization.setModel(model);

            List<EquipmentDto> equipments = equipmentController.findAllEquipments();
            List<RentalDto> rentals = rentalController.findAllRentals();

            int totalEquipment = 0;
            double totalUtilization = 0;
            String mostUtilized = "-";
            String leastUtilized = "-";
            double maxUtil = -1, minUtil = 101;

            for (EquipmentDto eq : equipments) {
                if (!"All Branches".equals(selectedBranch) && !selectedBranch.startsWith(eq.getBranchId())) continue;
                long daysRented = 0;
                for (RentalDto rental : rentals) {
                    if (!rental.getEquipmentId().equals(eq.getEquipmentId())) continue;
                    if (rental.getStartDate() == null || rental.getEndDate() == null) continue;
                    LocalDate rs = rental.getStartDate().isBefore(startDate) ? startDate : rental.getStartDate();
                    LocalDate re = rental.getEndDate().isAfter(endDate) ? endDate : rental.getEndDate();
                    if (!rs.isAfter(re)) daysRented += ChronoUnit.DAYS.between(rs, re) + 1;
                }
                long daysAvailable = totalDays - daysRented;
                double utilPct = totalDays > 0 ? Math.round((daysRented * 100.0) / totalDays) : 0;
                model.addRow(new Object[]{
                    eq.getEquipmentId(), eq.getBrand(), eq.getModel(),
                    eq.getCategoryId(), totalDays, daysRented, daysAvailable, utilPct + "%"
                });
                totalEquipment++;
                totalUtilization += utilPct;
                if (utilPct > maxUtil) { maxUtil = utilPct; mostUtilized = eq.getEquipmentId(); }
                if (utilPct < minUtil) { minUtil = utilPct; leastUtilized = eq.getEquipmentId(); }
            }

            double avg = totalEquipment > 0 ? Math.round(totalUtilization / totalEquipment) : 0;
            iblTotalEquipments.setText("Total Equipment : " + totalEquipment);
            iblAvgUtilization.setText("Avg Utilization : " + avg + "%");
            iblMostUtilization.setText("Most Utilized : " + mostUtilized);
            iblLeastUtilized.setText("Least Utilized : " + leastUtilized);

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Please use YYYY-MM-DD for From and To dates.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EquipmentUtilizationsReport().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JComboBox<String> cmbBranch;
    private javax.swing.JLabel iblAvgUtilization;
    private javax.swing.JLabel iblBranch;
    private javax.swing.JLabel iblFrom;
    private javax.swing.JTextField iblFromtxt;
    private javax.swing.JLabel iblHeader;
    private javax.swing.JLabel iblLeastUtilized;
    private javax.swing.JLabel iblMostUtilization;
    private javax.swing.JLabel iblTo;
    private javax.swing.JLabel iblTotalEquipments;
    private javax.swing.JTextField iblTotxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblequipmentzutilization;
    // End of variables declaration//GEN-END:variables
}