
package com.ijse.GearRentPro.view;

import com.ijse.GearRentPro.util.Session;
import javax.swing.JOptionPane;


public class MainDashboardView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboardView.class.getName());

    /**
     * Creates new form MainDashboardView
     */
    public MainDashboardView() {
        initComponents();
        applyRoleAccess();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblHeader = new javax.swing.JLabel();
        btnRental = new javax.swing.JButton();
        btnReservation = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnEquipment = new javax.swing.JButton();
        btnBranch = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        iblAdministration = new javax.swing.JLabel();
        btnMembership = new javax.swing.JButton();
        iblInventoryAndCustomers = new javax.swing.JLabel();
        iblOperations = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        iblOperations1 = new javax.swing.JLabel();
        btnOverdueRentals = new javax.swing.JButton();
        btnRevenueReport = new javax.swing.JButton();
        btnUtilizationReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iblHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        iblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iblHeader.setText("GearRentPro Dashboard");

        btnRental.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRental.setText("Rental");
        btnRental.addActionListener(this::btnRentalActionPerformed);

        btnReservation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReservation.setText("Reservation");
        btnReservation.addActionListener(this::btnReservationActionPerformed);

        btnCustomer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCustomer.setText("Customer");
        btnCustomer.addActionListener(this::btnCustomerActionPerformed);

        btnEquipment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEquipment.setText("Equipment");
        btnEquipment.addActionListener(this::btnEquipmentActionPerformed);

        btnBranch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBranch.setText("Branch");
        btnBranch.addActionListener(this::btnBranchActionPerformed);

        btnCategory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCategory.setText("Category");
        btnCategory.addActionListener(this::btnCategoryActionPerformed);

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUser.setText("User");
        btnUser.addActionListener(this::btnUserActionPerformed);

        iblAdministration.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblAdministration.setText("ADMINISTRATION");

        btnMembership.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMembership.setText("Membership");
        btnMembership.addActionListener(this::btnMembershipActionPerformed);

        iblInventoryAndCustomers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblInventoryAndCustomers.setText("INVENTORIES AND CUSTOMERS");

        iblOperations.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblOperations.setText("OPERATIONS");

        btnReturn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReturn.setText("Return");
        btnReturn.addActionListener(this::btnReturnActionPerformed);

        iblOperations1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblOperations1.setText("REPORTS AND MONITORING");

        btnOverdueRentals.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnOverdueRentals.setText("Overdue Rentals");
        btnOverdueRentals.addActionListener(this::btnOverdueRentalsActionPerformed);

        btnRevenueReport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRevenueReport.setText("RevenueReport");
        btnRevenueReport.addActionListener(this::btnRevenueReportActionPerformed);

        btnUtilizationReport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUtilizationReport.setText("Utilization Report");
        btnUtilizationReport.addActionListener(this::btnUtilizationReportActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iblOperations1)
                            .addComponent(iblOperations)
                            .addComponent(iblInventoryAndCustomers)
                            .addComponent(iblAdministration)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnRental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnMembership))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnOverdueRentals, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17)
                                    .addComponent(btnRevenueReport, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnUtilizationReport, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(iblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iblHeader)
                .addGap(26, 26, 26)
                .addComponent(iblAdministration, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(iblInventoryAndCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(iblOperations, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRental, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(iblOperations1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOverdueRentals, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRevenueReport, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUtilizationReport, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentalActionPerformed
        try {
            dispose();
            new RentalView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening Rental view: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRentalActionPerformed

    private void btnReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationActionPerformed
        try {
            dispose();
            new ReservationView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening Reservation view: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReservationActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        try {
            dispose();
            new CustomerView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening Customer view: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipmentActionPerformed
        try {
            dispose();
            new EquipmentView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening Equipment view: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEquipmentActionPerformed

    private void btnBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBranchActionPerformed
        try {
            dispose();
            new BranchView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening Branch view: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBranchActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        try {
            dispose();
            new CategoryView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening Category view: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            Session.clear();
            dispose();
            new LoginView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error during logout: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        try {
            dispose();
            new UserView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening User view: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMembershipActionPerformed
        dispose();
        new MembershipView().setVisible(true);
    }//GEN-LAST:event_btnMembershipActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        dispose();
        new ReturnView().setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnOverdueRentalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverdueRentalsActionPerformed
        dispose();
        new OverdueRentalsView().setVisible(true);

    }//GEN-LAST:event_btnOverdueRentalsActionPerformed

    private void btnRevenueReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueReportActionPerformed
        dispose();
        new BranchRevenueReportView().setVisible(true);
    }//GEN-LAST:event_btnRevenueReportActionPerformed

    private void btnUtilizationReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtilizationReportActionPerformed
        dispose();
        new EquipmentUtilizationsReport().setVisible(true);
    }//GEN-LAST:event_btnUtilizationReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboardView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBranch;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnEquipment;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMembership;
    private javax.swing.JButton btnOverdueRentals;
    private javax.swing.JButton btnRental;
    private javax.swing.JButton btnReservation;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnRevenueReport;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton btnUtilizationReport;
    private javax.swing.JLabel iblAdministration;
    private javax.swing.JLabel iblHeader;
    private javax.swing.JLabel iblInventoryAndCustomers;
    private javax.swing.JLabel iblOperations;
    private javax.swing.JLabel iblOperations1;
    // End of variables declaration//GEN-END:variables

    private void applyRoleAccess() {
        String roleId = Session.getLoggedInUser().getRoleId();

        if ("R001".equals(roleId)) {
            // ADMIN - no restrictions

        } else if ("R002".equals(roleId)) {
            // BRANCH_MANAGER
            btnBranch.setEnabled(false);
            btnUser.setEnabled(false);
            btnMembership.setEnabled(false);

        } else if ("R003".equals(roleId)) {
            // STAFF
            btnBranch.setEnabled(false);
            btnCategory.setEnabled(false);
            btnUser.setEnabled(false);
            btnMembership.setEnabled(false);
            btnRevenueReport.setEnabled(false);
            btnUtilizationReport.setEnabled(false);
        }
    }

}