package com.ijse.GearRentPro.view;

import com.ijse.GearRentPro.controller.MembershipController;
import com.ijse.GearRentPro.dto.MembershipDto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MembershipView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MembershipView.class.getName());
    private MembershipController membershipController = new MembershipController();

    /**
     * Creates new form MembershipView
     */
    public MembershipView() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblDelete = new javax.swing.JButton();
        iblMembershipId = new javax.swing.JLabel();
        iblMembDiscount = new javax.swing.JLabel();
        iblMembDiscounttxt = new javax.swing.JTextField();
        iblMembershipIdtxt = new javax.swing.JTextField();
        iblUpdate = new javax.swing.JButton();
        iblMembLevel = new javax.swing.JLabel();
        iblMembLeveltxt = new javax.swing.JTextField();
        iblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBranch = new javax.swing.JTable();
        iblSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iblDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblDelete.setText("Delete");
        iblDelete.addActionListener(this::iblDeleteActionPerformed);

        iblMembershipId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblMembershipId.setText("Membership ID");

        iblMembDiscount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblMembDiscount.setText("Discount %");

        iblMembDiscounttxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblMembDiscounttxt.addActionListener(this::iblMembDiscounttxtActionPerformed);

        iblMembershipIdtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        iblUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblUpdate.setText("Update");
        iblUpdate.addActionListener(this::iblUpdateActionPerformed);

        iblMembLevel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblMembLevel.setText("Level");

        iblMembLeveltxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblMembLeveltxt.addActionListener(this::iblMembLeveltxtActionPerformed);

        iblHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        iblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iblHeader.setText("Manage MemberShip");

        tblBranch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBranch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBranchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBranch);

        iblSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblSave.setText("Save");
        iblSave.addActionListener(this::iblSaveActionPerformed);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iblSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(iblMembershipId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(iblMembershipIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(iblMembLevel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(iblMembLeveltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(iblMembDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(iblMembDiscounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 479, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblMembershipId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblMembershipIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iblMembLevel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iblMembLeveltxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblMembDiscount)
                    .addComponent(iblMembDiscounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblSave)
                    .addComponent(iblDelete)
                    .addComponent(iblUpdate))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iblDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblDeleteActionPerformed
        deleteMembership();
    }//GEN-LAST:event_iblDeleteActionPerformed

    private void iblMembDiscounttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblMembDiscounttxtActionPerformed

    }//GEN-LAST:event_iblMembDiscounttxtActionPerformed

    private void iblUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblUpdateActionPerformed
        updateMembership();
    }//GEN-LAST:event_iblUpdateActionPerformed

    private void iblMembLeveltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblMembLeveltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblMembLeveltxtActionPerformed

    private void tblBranchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBranchMouseClicked
        searchMembership();
    }//GEN-LAST:event_tblBranchMouseClicked

    private void iblSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblSaveActionPerformed
        saveMembership();
    }//GEN-LAST:event_iblSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            dispose();
            new MainDashboardView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening Membership View : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void loadTable() {
        try {
            DefaultTableModel model = new DefaultTableModel(
                    new Object[]{"Membership ID", "Level", "Discount %"},
                    0
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            tblBranch.setModel(model);
            List<MembershipDto> memberships = membershipController.findAllMemberships();
            for (MembershipDto membership : memberships) {
                model.addRow(new Object[]{
                    membership.getMembershipId(),
                    membership.getLevel(),
                    membership.getDiscountPer()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading memberships: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void saveMembership() {
        try {
            if (iblMembershipIdtxt.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Membership ID is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (iblMembLeveltxt.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Membership level is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (iblMembDiscounttxt.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Discount percentage is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            MembershipDto dto = new MembershipDto(
                    iblMembershipIdtxt.getText(),
                    iblMembLeveltxt.getText(),
                    Double.parseDouble(iblMembDiscounttxt.getText())
            );

            boolean isSaved = membershipController.saveMembership(dto);
            if (isSaved) {
                JOptionPane.showMessageDialog(this, "Membership saved successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save membership.");
            }

            loadTable();
            clearForm();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Discount must be a valid number.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving membership: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateMembership() {
        try {
            if (iblMembershipIdtxt.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Membership ID is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (iblMembLeveltxt.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Membership level is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (iblMembDiscounttxt.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Discount percentage is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            MembershipDto dto = new MembershipDto(
                    iblMembershipIdtxt.getText(),
                    iblMembLeveltxt.getText(),
                    Double.parseDouble(iblMembDiscounttxt.getText())
            );

            boolean isUpdated = membershipController.updateMembership(dto);
            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Membership updated successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update membership.");
            }

            loadTable();
            clearForm();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Discount must be a valid number.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating membership: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deleteMembership() {
        try {
            String membershipId = iblMembershipIdtxt.getText();
            boolean isDeleted = membershipController.deleteMembership(membershipId);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Membership deleted successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete membership.");
            }

            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error deleting membership: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void searchMembership() {
        try {
            int selectedRow = tblBranch.getSelectedRow();
            if (selectedRow < 0) {
                return;
            }

            String membershipId = tblBranch.getValueAt(selectedRow, 0).toString();
            MembershipDto membership = membershipController.findMembership(membershipId);
            if (membership == null) {
                JOptionPane.showMessageDialog(this, "Membership not found.");
                return;
            }

            iblMembershipIdtxt.setText(membership.getMembershipId());
            iblMembLeveltxt.setText(membership.getLevel());
            iblMembDiscounttxt.setText(String.valueOf(membership.getDiscountPer()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error searching membership: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearForm() {
        iblMembershipIdtxt.setText("");
        iblMembLeveltxt.setText("");
        iblMembDiscounttxt.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MembershipView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton iblDelete;
    private javax.swing.JLabel iblHeader;
    private javax.swing.JLabel iblMembDiscount;
    private javax.swing.JTextField iblMembDiscounttxt;
    private javax.swing.JLabel iblMembLevel;
    private javax.swing.JTextField iblMembLeveltxt;
    private javax.swing.JLabel iblMembershipId;
    private javax.swing.JTextField iblMembershipIdtxt;
    private javax.swing.JButton iblSave;
    private javax.swing.JButton iblUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBranch;
    // End of variables declaration//GEN-END:variables
}
