
package com.ijse.GearRentPro.view;

import com.ijse.GearRentPro.controller.BranchController;
import com.ijse.GearRentPro.controller.CategoryController;
import com.ijse.GearRentPro.controller.CustomerController;
import com.ijse.GearRentPro.controller.EquipmentController;
import com.ijse.GearRentPro.controller.MembershipController;
import com.ijse.GearRentPro.controller.RentalController;
import com.ijse.GearRentPro.dto.BranchDto;
import com.ijse.GearRentPro.dto.CategoryDto;
import com.ijse.GearRentPro.dto.CustomerDto;
import com.ijse.GearRentPro.dto.EquipmentDto;
import com.ijse.GearRentPro.dto.MembershipDto;
import com.ijse.GearRentPro.dto.RentalDto;
import com.ijse.GearRentPro.util.Session;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class RentalView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentalView.class.getName());
    private RentalController rentalController = new RentalController();
    private EquipmentController equipmentController = new EquipmentController();
    private CustomerController customerController = new CustomerController();
    private BranchController branchController = new BranchController();
    private MembershipController membershipController = new MembershipController();
    private CategoryController categoryController = new CategoryController();

    /**
     * Creates new form RentalView
     */
    public RentalView() {
        initComponents();
        loadDropdowns();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblFinalAmounttxt = new javax.swing.JTextField();
        iblBrand = new javax.swing.JLabel();
        iblFinalAmount = new javax.swing.JLabel();
        iblUpdate = new javax.swing.JButton();
        iblStartDate = new javax.swing.JLabel();
        iblDelete = new javax.swing.JButton();
        iblStartDatetxt = new javax.swing.JTextField();
        iblSave = new javax.swing.JButton();
        iblHeader = new javax.swing.JLabel();
        iblEndDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbleRental = new javax.swing.JTable();
        iblRentalId = new javax.swing.JLabel();
        iblLongRentalDiscounttxt = new javax.swing.JTextField();
        iblRentalIdtxt = new javax.swing.JTextField();
        iblLongRentalDiscount = new javax.swing.JLabel();
        iblEquipmentid = new javax.swing.JLabel();
        iblEndDatetxt = new javax.swing.JTextField();
        iblDepositAmounttxt = new javax.swing.JTextField();
        iblCustomerId = new javax.swing.JLabel();
        iblMembershipDiscount = new javax.swing.JLabel();
        iblPaymentStatus = new javax.swing.JLabel();
        iblDepositAmount = new javax.swing.JLabel();
        iblRentalAmount = new javax.swing.JLabel();
        iblRentalAmounttxt = new javax.swing.JTextField();
        iblBaseDailyPricetxt = new javax.swing.JTextField();
        cmbEquipmentId = new javax.swing.JComboBox<>();
        cmbCustomerId = new javax.swing.JComboBox<>();
        cmbBranchId = new javax.swing.JComboBox<>();
        cmbPaymentStatus = new javax.swing.JComboBox<>();
        btnCalculate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iblFinalAmounttxt.setEditable(false);
        iblFinalAmounttxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        iblBrand.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblBrand.setText("Branch ID");

        iblFinalAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblFinalAmount.setText("Final Amount");

        iblUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblUpdate.setText("Update");
        iblUpdate.addActionListener(this::iblUpdateActionPerformed);

        iblStartDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblStartDate.setText("Start Date");

        iblDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblDelete.setText("Delete");
        iblDelete.addActionListener(this::iblDeleteActionPerformed);

        iblStartDatetxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblStartDatetxt.addActionListener(this::iblStartDatetxtActionPerformed);

        iblSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblSave.setText("Save");
        iblSave.addActionListener(this::iblSaveActionPerformed);

        iblHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        iblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iblHeader.setText("Manage Rental");

        iblEndDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblEndDate.setText("End Date");

        tbleRental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbleRental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleRentalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbleRental);

        iblRentalId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblRentalId.setText("Rental ID");

        iblLongRentalDiscounttxt.setEditable(false);
        iblLongRentalDiscounttxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblLongRentalDiscounttxt.addActionListener(this::iblLongRentalDiscounttxtActionPerformed);

        iblRentalIdtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblRentalIdtxt.addActionListener(this::iblRentalIdtxtActionPerformed);

        iblLongRentalDiscount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblLongRentalDiscount.setText("Long Rental Discount");

        iblEquipmentid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblEquipmentid.setText("Equipment ID");

        iblEndDatetxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        iblDepositAmounttxt.setEditable(false);
        iblDepositAmounttxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        iblCustomerId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCustomerId.setText("Customer ID");

        iblMembershipDiscount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblMembershipDiscount.setText("Membership Discount");

        iblPaymentStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblPaymentStatus.setText("Payment Status");

        iblDepositAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblDepositAmount.setText("Deposit Amount");

        iblRentalAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblRentalAmount.setText("Rental Amount");

        iblRentalAmounttxt.setEditable(false);
        iblRentalAmounttxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        iblBaseDailyPricetxt.setEditable(false);
        iblBaseDailyPricetxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        cmbEquipmentId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbEquipmentId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEquipmentId.addActionListener(this::cmbEquipmentIdActionPerformed);

        cmbCustomerId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbCustomerId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCustomerId.addActionListener(this::cmbCustomerIdActionPerformed);

        cmbBranchId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbBranchId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBranchId.addActionListener(this::cmbBranchIdActionPerformed);

        cmbPaymentStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbPaymentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paid", "Unpaid", "Partially Paid" }));
        cmbPaymentStatus.addActionListener(this::cmbPaymentStatusActionPerformed);

        btnCalculate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(iblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(48, 48, 48)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(iblEndDate)
                                                .addGap(56, 56, 56))
                                            .addComponent(iblEquipmentid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(iblPaymentStatus)))
                                .addComponent(iblRentalId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(iblStartDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(iblBrand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblCustomerId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iblStartDatetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(cmbCustomerId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEquipmentId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iblRentalIdtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(cmbBranchId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iblEndDatetxt)
                            .addComponent(cmbPaymentStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(iblMembershipDiscount, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(iblRentalAmount)
                                        .addComponent(iblDepositAmount))
                                    .addComponent(iblFinalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblLongRentalDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(iblFinalAmounttxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                    .addComponent(iblDepositAmounttxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(iblRentalAmounttxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(iblBaseDailyPricetxt)
                                    .addComponent(iblLongRentalDiscounttxt, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(iblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(iblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(iblSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(iblRentalAmounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iblHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(iblRentalIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(iblRentalId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(iblRentalAmount, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblDepositAmounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblDepositAmount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iblMembershipDiscount)
                            .addComponent(iblBaseDailyPricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblLongRentalDiscounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblLongRentalDiscount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iblFinalAmount)
                            .addComponent(iblFinalAmounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbEquipmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblEquipmentid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblBrand)
                            .addComponent(cmbBranchId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblCustomerId)
                            .addComponent(cmbCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iblStartDate)
                            .addComponent(iblStartDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblEndDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblEndDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iblPaymentStatus)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 69, Short.MAX_VALUE)
                        .addComponent(btnCalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblDelete)
                            .addComponent(iblUpdate)
                            .addComponent(iblSave))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnBack)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iblUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblUpdateActionPerformed
        updateRental();
    }//GEN-LAST:event_iblUpdateActionPerformed

    private void iblDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblDeleteActionPerformed
        deleteRental();
    }//GEN-LAST:event_iblDeleteActionPerformed

    private void iblStartDatetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblStartDatetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblStartDatetxtActionPerformed

    private void iblSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblSaveActionPerformed
        saveRental();
    }//GEN-LAST:event_iblSaveActionPerformed

    private void tbleRentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleRentalMouseClicked
        searchRental();
    }//GEN-LAST:event_tbleRentalMouseClicked

    private void iblLongRentalDiscounttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblLongRentalDiscounttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblLongRentalDiscounttxtActionPerformed

    private void iblRentalIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblRentalIdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblRentalIdtxtActionPerformed

    private void cmbEquipmentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEquipmentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEquipmentIdActionPerformed

    private void cmbCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCustomerIdActionPerformed

    private void cmbBranchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBranchIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBranchIdActionPerformed

    private void cmbPaymentStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaymentStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPaymentStatusActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        calculateRental();
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            dispose();
            new MainDashboardView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening Rental View : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void loadDropdowns() {
        try {
            cmbEquipmentId.removeAllItems();
            cmbCustomerId.removeAllItems();
            cmbBranchId.removeAllItems();
            cmbPaymentStatus.removeAllItems();

            cmbBranchId.addItem("All Branches");
            cmbPaymentStatus.addItem("All");
            cmbPaymentStatus.addItem("Paid");
            cmbPaymentStatus.addItem("Unpaid");
            cmbPaymentStatus.addItem("Partially Paid");

            List<EquipmentDto> equipments = equipmentController.findAllEquipments();
            for (EquipmentDto equipment : equipments) {
                cmbEquipmentId.addItem(equipment.getEquipmentId());
            }

            List<CustomerDto> customers = customerController.findAllCustomers();
            for (CustomerDto customer : customers) {
                cmbCustomerId.addItem(customer.getCustomerId());
            }

            List<BranchDto> branches = branchController.findAllBranches();
            for (BranchDto branch : branches) {
                cmbBranchId.addItem(branch.getBranchId());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading dropdowns: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void calculateRental() {
        try {
            String equipmentId = cmbEquipmentId.getSelectedItem().toString();
            String customerId = cmbCustomerId.getSelectedItem().toString();

            EquipmentDto equipment = equipmentController.findEquipment(equipmentId);
            CustomerDto customer = customerController.findCustomer(customerId);
            CategoryDto category = categoryController.findCategory(equipment.getCategoryId());

            LocalDate startDate = LocalDate.parse(iblStartDatetxt.getText());
            LocalDate endDate = LocalDate.parse(iblEndDatetxt.getText());

            long days = ChronoUnit.DAYS.between(startDate, endDate);
            // Count weekend days
            long weekendDays = 0;
            for (LocalDate d = startDate; d.isBefore(endDate); d = d.plusDays(1)) {
                if (d.getDayOfWeek() == DayOfWeek.SATURDAY
                        || d.getDayOfWeek() == DayOfWeek.SUNDAY) {
                    weekendDays++;
                }
            }
            long weekDays = days - weekendDays;

            double priceFactor = category.getPriceFactor();
            double weekendMultiplier = category.getWeekendMultiplier();
            double basePrice = equipment.getBaseDailyPrice();

            double rentalAmount = (basePrice * priceFactor * weekDays)
                    + (basePrice * priceFactor * weekendMultiplier * weekendDays);
            double depositAmount = equipment.getSecurityDeposit();

            MembershipDto membership = null;
            if (customer != null && customer.getMembershipId() != null && !customer.getMembershipId().isBlank()) {
                membership = membershipController.findMembership(customer.getMembershipId());
            }

            double membershipDiscount = membership != null ? rentalAmount * (membership.getDiscountPer() / 100.0) : 0.0;
            double longRentalDiscount = days >= 7 ? rentalAmount * 0.10 : 0.0;
            double finalAmount = rentalAmount - membershipDiscount - longRentalDiscount;

            iblRentalAmounttxt.setText(String.valueOf(rentalAmount));
            iblDepositAmounttxt.setText(String.valueOf(depositAmount));
            iblBaseDailyPricetxt.setText(String.valueOf(membershipDiscount));
            iblLongRentalDiscounttxt.setText(String.valueOf(longRentalDiscount));
            iblFinalAmounttxt.setText(String.valueOf(finalAmount));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error calculating rental: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadTable() {
        try {
            DefaultTableModel model = new DefaultTableModel(
                    new Object[]{"Rental ID", "Equipment ID", "Customer ID", "Branch ID", "Start Date", "End Date", "Rental Amount", "Final Amount", "Payment Status", "Rental Status"},
                    0
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            tbleRental.setModel(model);

            List<RentalDto> rentals = rentalController.findAllRentals();
            String branchFilter = Session.getCurrentBranchId();
            String selectedBranch = cmbBranchId.getSelectedItem() != null ? cmbBranchId.getSelectedItem().toString() : "";
            String paymentFilter = cmbPaymentStatus.getSelectedItem() != null ? cmbPaymentStatus.getSelectedItem().toString() : "";
            LocalDate startFilter = null;
            LocalDate endFilter = null;
            if (!iblStartDatetxt.getText().trim().isBlank()) {
                startFilter = LocalDate.parse(iblStartDatetxt.getText().trim());
            }
            if (!iblEndDatetxt.getText().trim().isBlank()) {
                endFilter = LocalDate.parse(iblEndDatetxt.getText().trim());
            }
            for (RentalDto rental : rentals) {
                if (branchFilter != null && !branchFilter.equals(rental.getBranchId())) {
                    continue;
                }
                if (!selectedBranch.isBlank() && !"All Branches".equals(selectedBranch) && !selectedBranch.startsWith(rental.getBranchId())) {
                    continue;
                }
                if (startFilter != null && rental.getStartDate() != null && rental.getStartDate().isBefore(startFilter)) {
                    continue;
                }
                if (endFilter != null && rental.getEndDate() != null && rental.getEndDate().isAfter(endFilter)) {
                    continue;
                }
                if (!paymentFilter.isBlank() && !"All".equalsIgnoreCase(paymentFilter) && !rental.getPaymentStatus().equalsIgnoreCase(paymentFilter)) {
                    continue;
                }
                model.addRow(new Object[]{
                    rental.getRentalId(),
                    rental.getEquipmentId(),
                    rental.getCustomerId(),
                    rental.getBranchId(),
                    rental.getStartDate(),
                    rental.getEndDate(),
                    rental.getRentalAmount(),
                    rental.getFinalAmount(),
                    rental.getPaymentStatus(),
                    rental.getRentalStatus()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading rentals: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void saveRental() {
        try {
            if (iblRentalIdtxt.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Rental ID is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (cmbEquipmentId.getSelectedItem() == null || cmbCustomerId.getSelectedItem() == null || cmbBranchId.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Equipment, customer, and branch must be selected.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            RentalDto dto = new RentalDto(
                    iblRentalIdtxt.getText(),
                    cmbEquipmentId.getSelectedItem().toString(),
                    cmbCustomerId.getSelectedItem().toString(),
                    cmbBranchId.getSelectedItem().toString(),
                    LocalDate.parse(iblStartDatetxt.getText()),
                    LocalDate.parse(iblEndDatetxt.getText()),
                    null,
                    Double.parseDouble(iblRentalAmounttxt.getText()),
                    Double.parseDouble(iblDepositAmounttxt.getText()),
                    Double.parseDouble(iblBaseDailyPricetxt.getText()),
                    Double.parseDouble(iblLongRentalDiscounttxt.getText()),
                    Double.parseDouble(iblFinalAmounttxt.getText()),
                        resolvePaymentStatusForSave(),
                    "Active"
            );

            boolean isSaved = rentalController.saveRental(dto);
            if (isSaved) {
                JOptionPane.showMessageDialog(this, "Rental saved successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save rental.");
            }

            clearForm();
            loadTable();
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Start date and end date must be in YYYY-MM-DD format.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Amount fields must contain valid numeric values.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving rental: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateRental() {
        try {
            if (iblRentalIdtxt.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Rental ID is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (cmbEquipmentId.getSelectedItem() == null || cmbCustomerId.getSelectedItem() == null || cmbBranchId.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Equipment, customer, and branch must be selected.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            RentalDto dto = new RentalDto(
                    iblRentalIdtxt.getText(),
                    cmbEquipmentId.getSelectedItem().toString(),
                    cmbCustomerId.getSelectedItem().toString(),
                    cmbBranchId.getSelectedItem().toString(),
                    LocalDate.parse(iblStartDatetxt.getText()),
                    LocalDate.parse(iblEndDatetxt.getText()),
                    null,
                    Double.parseDouble(iblRentalAmounttxt.getText()),
                    Double.parseDouble(iblDepositAmounttxt.getText()),
                    Double.parseDouble(iblBaseDailyPricetxt.getText()),
                    Double.parseDouble(iblLongRentalDiscounttxt.getText()),
                    Double.parseDouble(iblFinalAmounttxt.getText()),
                        resolvePaymentStatusForSave(),
                    "Active"
            );

            boolean isUpdated = rentalController.updateRental(dto);
            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Rental updated successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update rental.");
            }

            clearForm();
            loadTable();
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Start date and end date must be in YYYY-MM-DD format.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Amount fields must contain valid numeric values.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating rental: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deleteRental() {
        try {
            String rentalId = iblRentalIdtxt.getText();
            if (rentalId.isBlank()) {
                JOptionPane.showMessageDialog(this, "Please enter or select a rental ID to delete.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            boolean isDeleted = rentalController.deleteRental(rentalId);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Rental deleted successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete rental.");
            }

            clearForm();
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error deleting rental: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void searchRental() {
        try {
            int selectedRow = tbleRental.getSelectedRow();
            if (selectedRow < 0) {
                return;
            }

            String rentalId = tbleRental.getValueAt(selectedRow, 0).toString();
            RentalDto rental = rentalController.findRental(rentalId);
            if (rental == null) {
                JOptionPane.showMessageDialog(this, "Rental not found.");
                return;
            }

            iblRentalIdtxt.setText(rental.getRentalId());
            cmbEquipmentId.setSelectedItem(rental.getEquipmentId());
            cmbCustomerId.setSelectedItem(rental.getCustomerId());
            cmbBranchId.setSelectedItem(rental.getBranchId());
            iblStartDatetxt.setText(rental.getStartDate().toString());
            iblEndDatetxt.setText(rental.getEndDate().toString());
            iblRentalAmounttxt.setText(String.valueOf(rental.getRentalAmount()));
            iblDepositAmounttxt.setText(String.valueOf(rental.getDepositAmount()));
            iblBaseDailyPricetxt.setText(String.valueOf(rental.getMembershipDiscount()));
            iblLongRentalDiscounttxt.setText(String.valueOf(rental.getLongRentalDiscount()));
            iblFinalAmounttxt.setText(String.valueOf(rental.getFinalAmount()));
            cmbPaymentStatus.setSelectedItem(rental.getPaymentStatus());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error searching rental: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearForm() {
        iblRentalIdtxt.setText("");
        iblStartDatetxt.setText("");
        iblEndDatetxt.setText("");
        iblRentalAmounttxt.setText("");
        iblDepositAmounttxt.setText("");
        iblBaseDailyPricetxt.setText("");
        iblLongRentalDiscounttxt.setText("");
        iblFinalAmounttxt.setText("");

        if (cmbEquipmentId.getItemCount() > 0) {
            cmbEquipmentId.setSelectedIndex(0);
        }
        if (cmbCustomerId.getItemCount() > 0) {
            cmbCustomerId.setSelectedIndex(0);
        }
        if (cmbBranchId.getItemCount() > 0) {
            cmbBranchId.setSelectedIndex(0);
        }
        if (cmbPaymentStatus.getItemCount() > 0) {
            cmbPaymentStatus.setSelectedIndex(0);
        }
    }

    private String resolvePaymentStatusForSave() {
        String selected = cmbPaymentStatus.getSelectedItem() != null ? cmbPaymentStatus.getSelectedItem().toString() : "";
        return "All".equalsIgnoreCase(selected) ? "Unpaid" : selected;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RentalView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JComboBox<String> cmbBranchId;
    private javax.swing.JComboBox<String> cmbCustomerId;
    private javax.swing.JComboBox<String> cmbEquipmentId;
    private javax.swing.JComboBox<String> cmbPaymentStatus;
    private javax.swing.JTextField iblBaseDailyPricetxt;
    private javax.swing.JLabel iblBrand;
    private javax.swing.JLabel iblCustomerId;
    private javax.swing.JButton iblDelete;
    private javax.swing.JLabel iblDepositAmount;
    private javax.swing.JTextField iblDepositAmounttxt;
    private javax.swing.JLabel iblEndDate;
    private javax.swing.JTextField iblEndDatetxt;
    private javax.swing.JLabel iblEquipmentid;
    private javax.swing.JLabel iblFinalAmount;
    private javax.swing.JTextField iblFinalAmounttxt;
    private javax.swing.JLabel iblHeader;
    private javax.swing.JLabel iblLongRentalDiscount;
    private javax.swing.JTextField iblLongRentalDiscounttxt;
    private javax.swing.JLabel iblMembershipDiscount;
    private javax.swing.JLabel iblPaymentStatus;
    private javax.swing.JLabel iblRentalAmount;
    private javax.swing.JTextField iblRentalAmounttxt;
    private javax.swing.JLabel iblRentalId;
    private javax.swing.JTextField iblRentalIdtxt;
    private javax.swing.JButton iblSave;
    private javax.swing.JLabel iblStartDate;
    private javax.swing.JTextField iblStartDatetxt;
    private javax.swing.JButton iblUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbleRental;
    // End of variables declaration//GEN-END:variables
}