/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ijse.GearRentPro.view;

import com.ijse.GearRentPro.controller.BranchController;
import com.ijse.GearRentPro.controller.CustomerController;
import com.ijse.GearRentPro.controller.EquipmentController;
import com.ijse.GearRentPro.controller.ReservationController;
import com.ijse.GearRentPro.dto.ReservationDto;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ReservationView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReservationView.class.getName());
    private ReservationController reservationController = new ReservationController();
    private EquipmentController equipmentController = new EquipmentController();
    private CustomerController customerController = new CustomerController();
    private BranchController branchController = new BranchController();

    /**
     * Creates new form ReservationView
     */
    public ReservationView() {
        initComponents();
        loadDropdowns();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblReservationId = new javax.swing.JLabel();
        iblSave = new javax.swing.JButton();
        iblResCustomerId = new javax.swing.JLabel();
        iblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservation = new javax.swing.JTable();
        iblStartDate = new javax.swing.JLabel();
        iblResStatus = new javax.swing.JLabel();
        iblResBranchId = new javax.swing.JLabel();
        iblEndDate = new javax.swing.JLabel();
        iblStartDatetxt = new javax.swing.JTextField();
        iblResStatustxt = new javax.swing.JTextField();
        iblReservationIdtxt = new javax.swing.JTextField();
        iblEndDatetxt = new javax.swing.JTextField();
        iblUpdate = new javax.swing.JButton();
        iblResEquipId = new javax.swing.JLabel();
        iblDelete = new javax.swing.JButton();
        cmbEquipmentId = new javax.swing.JComboBox<>();
        cmbBranchId = new javax.swing.JComboBox<>();
        cmbCustomerId = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iblReservationId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblReservationId.setText("Reservation ID");

        iblSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblSave.setText("Save");
        iblSave.addActionListener(this::iblSaveActionPerformed);

        iblResCustomerId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblResCustomerId.setText("Customer ID");

        iblHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        iblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iblHeader.setText("Manage Reservation");

        tblReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReservationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReservation);

        iblStartDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblStartDate.setText("Start Date");

        iblResStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblResStatus.setText("Status");

        iblResBranchId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblResBranchId.setText("Branch ID");

        iblEndDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblEndDate.setText("End Date");

        iblStartDatetxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblStartDatetxt.addActionListener(this::iblStartDatetxtActionPerformed);

        iblResStatustxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblResStatustxt.addActionListener(this::iblResStatustxtActionPerformed);

        iblReservationIdtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        iblEndDatetxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iblEndDatetxt.addActionListener(this::iblEndDatetxtActionPerformed);

        iblUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblUpdate.setText("Update");
        iblUpdate.addActionListener(this::iblUpdateActionPerformed);

        iblResEquipId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblResEquipId.setText("Equipment ID");

        iblDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblDelete.setText("Delete");
        iblDelete.addActionListener(this::iblDeleteActionPerformed);

        cmbEquipmentId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEquipmentId.addActionListener(this::cmbEquipmentIdActionPerformed);

        cmbBranchId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBranchId.addActionListener(this::cmbBranchIdActionPerformed);

        cmbCustomerId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCustomerId.addActionListener(this::cmbCustomerIdActionPerformed);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iblSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(iblReservationId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(iblReservationIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(iblEndDate)
                                            .addComponent(iblStartDate)
                                            .addComponent(iblResStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(iblResBranchId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(iblResCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(iblResEquipId))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(iblStartDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(cmbCustomerId, javax.swing.GroupLayout.Alignment.TRAILING, 0, 205, Short.MAX_VALUE)
                                                        .addComponent(cmbBranchId, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cmbEquipmentId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(iblEndDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(iblResStatustxt))))
                                .addGap(434, 434, 434)))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iblReservationId)
                    .addComponent(iblReservationIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblResEquipId)
                    .addComponent(cmbEquipmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iblResCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblResBranchId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbBranchId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblStartDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblEndDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblResStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblResStatustxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblDelete)
                    .addComponent(iblUpdate)
                    .addComponent(iblSave))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iblSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblSaveActionPerformed
        saveReservation();
    }//GEN-LAST:event_iblSaveActionPerformed

    private void tblReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReservationMouseClicked
        searchReservation();
    }//GEN-LAST:event_tblReservationMouseClicked

    private void iblStartDatetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblStartDatetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblStartDatetxtActionPerformed

    private void iblResStatustxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblResStatustxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblResStatustxtActionPerformed

    private void iblEndDatetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblEndDatetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblEndDatetxtActionPerformed

    private void iblUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblUpdateActionPerformed
        updateReservation();
    }//GEN-LAST:event_iblUpdateActionPerformed

    private void iblDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblDeleteActionPerformed
        deleteReservation();
    }//GEN-LAST:event_iblDeleteActionPerformed

    private void cmbBranchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBranchIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBranchIdActionPerformed

    private void cmbCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCustomerIdActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            dispose();
            new MainDashboardView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening Reservation View : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbEquipmentIdActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void loadDropdowns() {
        try {
            cmbEquipmentId.removeAllItems();
            cmbCustomerId.removeAllItems();
            cmbBranchId.removeAllItems();

            List<com.ijse.GearRentPro.dto.EquipmentDto> equipments = equipmentController.findAllEquipments();
            for (com.ijse.GearRentPro.dto.EquipmentDto equipment : equipments) {
                cmbEquipmentId.addItem(equipment.getEquipmentId());
            }

            List<com.ijse.GearRentPro.dto.CustomerDto> customers = customerController.findAllCustomers();
            for (com.ijse.GearRentPro.dto.CustomerDto customer : customers) {
                cmbCustomerId.addItem(customer.getCustomerId());
            }

            List<com.ijse.GearRentPro.dto.BranchDto> branches = branchController.findAllBranches();
            for (com.ijse.GearRentPro.dto.BranchDto branch : branches) {
                cmbBranchId.addItem(branch.getBranchId());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading dropdowns: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadTable() {
        try {
            DefaultTableModel model = new DefaultTableModel(
                    new Object[]{"Reservation ID", "Equipment ID", "Customer ID", "Branch ID", "Start Date", "End Date", "Status"},
                    0
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            tblReservation.setModel(model);

            List<ReservationDto> reservations = reservationController.findAllReservations();
            for (ReservationDto reservation : reservations) {
                model.addRow(new Object[]{
                    reservation.getReservationId(),
                    reservation.getEquipmentId(),
                    reservation.getCustomerId(),
                    reservation.getBranchId(),
                    reservation.getStartDate(),
                    reservation.getEndDate(),
                    reservation.getReservationStatus()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading reservations: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void saveReservation() {
        try {
            ReservationDto dto = new ReservationDto(
                    iblReservationIdtxt.getText(),
                    cmbEquipmentId.getSelectedItem().toString(),
                    cmbCustomerId.getSelectedItem().toString(),
                    cmbBranchId.getSelectedItem().toString(),
                    LocalDate.parse(iblStartDatetxt.getText()),
                    LocalDate.parse(iblEndDatetxt.getText()),
                    iblResStatustxt.getText()
            );

            boolean isSaved = reservationController.saveReservation(dto);
            if (isSaved) {
                JOptionPane.showMessageDialog(this, "Reservation saved successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save reservation.");
            }

            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving reservation: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateReservation() {
        try {
            ReservationDto dto = new ReservationDto(
                    iblReservationIdtxt.getText(),
                    cmbEquipmentId.getSelectedItem().toString(),
                    cmbCustomerId.getSelectedItem().toString(),
                    cmbBranchId.getSelectedItem().toString(),
                    LocalDate.parse(iblStartDatetxt.getText()),
                    LocalDate.parse(iblEndDatetxt.getText()),
                    iblResStatustxt.getText()
            );

            boolean isUpdated = reservationController.updateReservation(dto);
            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Reservation updated successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update reservation.");
            }

            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating reservation: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deleteReservation() {
        try {
            String reservationId = iblReservationIdtxt.getText();
            boolean isDeleted = reservationController.deleteReservation(reservationId);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Reservation deleted successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete reservation.");
            }

            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error deleting reservation: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void searchReservation() {
        try {
            int selectedRow = tblReservation.getSelectedRow();
            if (selectedRow < 0) {
                return;
            }

            String reservationId = tblReservation.getValueAt(selectedRow, 0).toString();
            ReservationDto reservation = reservationController.findReservation(reservationId);
            if (reservation == null) {
                JOptionPane.showMessageDialog(this, "Reservation not found.");
                return;
            }

            iblReservationIdtxt.setText(reservation.getReservationId());
            cmbEquipmentId.setSelectedItem(reservation.getEquipmentId());
            cmbCustomerId.setSelectedItem(reservation.getCustomerId());
            cmbBranchId.setSelectedItem(reservation.getBranchId());
            iblStartDatetxt.setText(reservation.getStartDate().toString());
            iblEndDatetxt.setText(reservation.getEndDate().toString());
            iblResStatustxt.setText(reservation.getReservationStatus());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error searching reservation: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearForm() {
        iblReservationIdtxt.setText("");
        iblStartDatetxt.setText("");
        iblEndDatetxt.setText("");
        iblResStatustxt.setText("");
        if (cmbEquipmentId.getItemCount() > 0) {
            cmbEquipmentId.setSelectedIndex(0);
        }
        if (cmbCustomerId.getItemCount() > 0) {
            cmbCustomerId.setSelectedIndex(0);
        }
        if (cmbBranchId.getItemCount() > 0) {
            cmbBranchId.setSelectedIndex(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReservationView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbBranchId;
    private javax.swing.JComboBox<String> cmbCustomerId;
    private javax.swing.JComboBox<String> cmbEquipmentId;
    private javax.swing.JButton iblDelete;
    private javax.swing.JLabel iblEndDate;
    private javax.swing.JTextField iblEndDatetxt;
    private javax.swing.JLabel iblHeader;
    private javax.swing.JLabel iblResBranchId;
    private javax.swing.JLabel iblResCustomerId;
    private javax.swing.JLabel iblResEquipId;
    private javax.swing.JLabel iblResStatus;
    private javax.swing.JTextField iblResStatustxt;
    private javax.swing.JLabel iblReservationId;
    private javax.swing.JTextField iblReservationIdtxt;
    private javax.swing.JButton iblSave;
    private javax.swing.JLabel iblStartDate;
    private javax.swing.JTextField iblStartDatetxt;
    private javax.swing.JButton iblUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReservation;
    // End of variables declaration//GEN-END:variables

}
