package com.ijse.GearRentPro.view;

import com.ijse.GearRentPro.controller.CategoryController;
import com.ijse.GearRentPro.controller.EquipmentController;
import com.ijse.GearRentPro.controller.RentalController;
import com.ijse.GearRentPro.dto.CategoryDto;
import com.ijse.GearRentPro.dto.EquipmentDto;
import com.ijse.GearRentPro.dto.RentalDto;
import com.ijse.GearRentPro.util.Session;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ReturnView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReturnView.class.getName());
    private RentalController rentalController = new RentalController();
    private CategoryController categoryController = new CategoryController();
    private EquipmentController equipmentController = new EquipmentController();

    /**
     * Creates new form ReturnView
     */
    public ReturnView() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        loadDropdowns();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblActualReturnDatetxt = new javax.swing.JTextField();
        iblRentalId = new javax.swing.JLabel();
        iblSave = new javax.swing.JButton();
        iblCatDes = new javax.swing.JLabel();
        iblHeader = new javax.swing.JLabel();
        iblDamageDescptxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReturn = new javax.swing.JTable();
        iblCatDestxt = new javax.swing.JTextField();
        iblDamageCharge = new javax.swing.JLabel();
        iblTotalCharges = new javax.swing.JLabel();
        iblDamageDescp = new javax.swing.JLabel();
        iblCatLateFeeperday = new javax.swing.JLabel();
        iblDamageChargetxt = new javax.swing.JTextField();
        iblLateFeetxt = new javax.swing.JTextField();
        iblCatLateFeeperdaytxt = new javax.swing.JTextField();
        iblUpdate = new javax.swing.JButton();
        iblActualReturnDate = new javax.swing.JLabel();
        iblDelete = new javax.swing.JButton();
        cmbRentalId = new javax.swing.JComboBox<>();
        iblRefund = new javax.swing.JLabel();
        iblLateFee = new javax.swing.JLabel();
        iblRefundtxt = new javax.swing.JTextField();
        iblTotalChargestxt = new javax.swing.JTextField();
        btnprocessReturn = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iblActualReturnDatetxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblActualReturnDatetxt.addActionListener(this::iblActualReturnDatetxtActionPerformed);

        iblRentalId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblRentalId.setText("Rental ID");

        iblSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblSave.setText("Save");
        iblSave.addActionListener(this::iblSaveActionPerformed);

        iblCatDes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCatDes.setText("Damage ID");

        iblHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        iblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iblHeader.setText("Process Return");

        iblDamageDescptxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblDamageDescptxt.addActionListener(this::iblDamageDescptxtActionPerformed);

        tblReturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReturnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReturn);

        iblCatDestxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCatDestxt.addActionListener(this::iblCatDestxtActionPerformed);

        iblDamageCharge.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblDamageCharge.setText("Damage Charge");

        iblTotalCharges.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblTotalCharges.setText("Total Charges");

        iblDamageDescp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblDamageDescp.setText("Description");

        iblCatLateFeeperday.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCatLateFeeperday.setText("Late Fee Per Day");

        iblDamageChargetxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblDamageChargetxt.addActionListener(this::iblDamageChargetxtActionPerformed);

        iblLateFeetxt.setEditable(false);
        iblLateFeetxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblLateFeetxt.addActionListener(this::iblLateFeetxtActionPerformed);

        iblCatLateFeeperdaytxt.setEditable(false);
        iblCatLateFeeperdaytxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblCatLateFeeperdaytxt.addActionListener(this::iblCatLateFeeperdaytxtActionPerformed);

        iblUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblUpdate.setText("Update");
        iblUpdate.addActionListener(this::iblUpdateActionPerformed);

        iblActualReturnDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblActualReturnDate.setText("Actual Return Date");

        iblDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblDelete.setText("Delete");
        iblDelete.addActionListener(this::iblDeleteActionPerformed);

        cmbRentalId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbRentalId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRentalId.addActionListener(this::cmbRentalIdActionPerformed);

        iblRefund.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblRefund.setText("Refund / Extra Pay");

        iblLateFee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblLateFee.setText("Late Fee");

        iblRefundtxt.setEditable(false);
        iblRefundtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblRefundtxt.addActionListener(this::iblRefundtxtActionPerformed);

        iblTotalChargestxt.setEditable(false);
        iblTotalChargestxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblTotalChargestxt.addActionListener(this::iblTotalChargestxtActionPerformed);

        btnprocessReturn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnprocessReturn.setText("Process Return");
        btnprocessReturn.addActionListener(this::btnprocessReturnActionPerformed);

        btnCalculate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnprocessReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iblSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iblCatLateFeeperday)
                    .addComponent(iblDamageCharge)
                    .addComponent(iblDamageDescp, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblCatDes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblActualReturnDate)
                    .addComponent(iblRentalId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblLateFee, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblTotalCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblRefund, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbRentalId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iblDamageChargetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                .addComponent(iblActualReturnDatetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                            .addComponent(iblCatDestxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblDamageDescptxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iblLateFeetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblRefundtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblTotalChargestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(iblCatLateFeeperdaytxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(601, 601, 601))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(iblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iblRentalId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbRentalId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblActualReturnDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblActualReturnDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblCatDestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblCatDes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblDamageDescptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblDamageDescp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblDamageChargetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblDamageCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblCatLateFeeperday, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblCatLateFeeperdaytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblLateFeetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblLateFee, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(iblRefund, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblTotalChargestxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblTotalCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iblRefundtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblDelete)
                    .addComponent(iblUpdate)
                    .addComponent(iblSave)
                    .addComponent(btnprocessReturn)
                    .addComponent(btnCalculate))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iblActualReturnDatetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblActualReturnDatetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblActualReturnDatetxtActionPerformed

    private void iblSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblSaveActionPerformed
        processReturn();
    }//GEN-LAST:event_iblSaveActionPerformed

    private void iblDamageDescptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblDamageDescptxtActionPerformed

    }//GEN-LAST:event_iblDamageDescptxtActionPerformed

    private void tblReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReturnMouseClicked
        int selectedRow = tblReturn.getSelectedRow();
        if (selectedRow >= 0) {
            String rentalId = tblReturn.getValueAt(selectedRow, 0).toString();
            cmbRentalId.setSelectedItem(rentalId);
        }
    }//GEN-LAST:event_tblReturnMouseClicked

    private void iblCatDestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblCatDestxtActionPerformed

    }//GEN-LAST:event_iblCatDestxtActionPerformed

    private void iblDamageChargetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblDamageChargetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblDamageChargetxtActionPerformed

    private void iblLateFeetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblLateFeetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblLateFeetxtActionPerformed

    private void iblCatLateFeeperdaytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblCatLateFeeperdaytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblCatLateFeeperdaytxtActionPerformed

    private void iblUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblUpdateActionPerformed
        processReturn();
    }//GEN-LAST:event_iblUpdateActionPerformed

    private void iblDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblDeleteActionPerformed
        clearForm();
    }//GEN-LAST:event_iblDeleteActionPerformed

    private void cmbRentalIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRentalIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRentalIdActionPerformed

    private void iblRefundtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblRefundtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblRefundtxtActionPerformed

    private void iblTotalChargestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblTotalChargestxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblTotalChargestxtActionPerformed

    private void btnprocessReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocessReturnActionPerformed
        processReturn();
    }//GEN-LAST:event_btnprocessReturnActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        calculateReturn();
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            dispose();
            new MainDashboardView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening Return View : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void loadDropdowns() {
        try {
            cmbRentalId.removeAllItems();
            List<RentalDto> rentals = rentalController.findAllRentals();
            String branchFilter = Session.getCurrentBranchId();
            for (RentalDto rental : rentals) {
                if (branchFilter != null && !branchFilter.equals(rental.getBranchId())) {
                    continue;
                }
                if ("Active".equalsIgnoreCase(rental.getRentalStatus())) {
                    cmbRentalId.addItem(rental.getRentalId());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading rental IDs: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadTable() {
        try {
            DefaultTableModel model = new DefaultTableModel(
                    new Object[]{"Rental ID", "Equipment ID", "Customer ID", "Start Date", "End Date", "Rental Status", "Payment Status"},
                    0
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            tblReturn.setModel(model);
            List<RentalDto> rentals = rentalController.findAllRentals();
            String branchFilter = Session.getCurrentBranchId();
            for (RentalDto rental : rentals) {
                if (branchFilter != null && !branchFilter.equals(rental.getBranchId())) {
                    continue;
                }
                model.addRow(new Object[]{
                    rental.getRentalId(),
                    rental.getEquipmentId(),
                    rental.getCustomerId(),
                    rental.getStartDate(),
                    rental.getEndDate(),
                    rental.getRentalStatus(),
                    rental.getPaymentStatus()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading return table: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void calculateReturn() {
        try {
            if (cmbRentalId.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Please select a rental ID.");
                return;
            }

            String rentalId = cmbRentalId.getSelectedItem().toString();
            RentalDto rental = rentalController.findRental(rentalId);
            if (rental == null) {
                JOptionPane.showMessageDialog(this, "Rental not found.");
                return;
            }

            LocalDate actualReturnDate = LocalDate.parse(iblActualReturnDatetxt.getText());
            long overdueDays = actualReturnDate.isAfter(rental.getEndDate())
                    ? ChronoUnit.DAYS.between(rental.getEndDate(), actualReturnDate)
                    : 0;

            EquipmentDto equipment = equipmentController.findEquipment(rental.getEquipmentId());
            CategoryDto category = categoryController.findCategory(equipment.getCategoryId());
            double lateFeePerDay = category != null ? category.getLateFeePerDay() : 0.0;
            double lateFee = overdueDays * lateFeePerDay;

            double damageCharge = iblDamageChargetxt.getText().isBlank()
                    ? 0.0
                    : Double.parseDouble(iblDamageChargetxt.getText());

            double totalCharges = lateFee + damageCharge;
            double refund = rental.getDepositAmount() - totalCharges;

            iblCatLateFeeperdaytxt.setText(String.valueOf(lateFeePerDay));
            iblLateFeetxt.setText(String.valueOf(lateFee));
            iblTotalChargestxt.setText(String.valueOf(totalCharges));
            iblRefundtxt.setText(String.valueOf(refund));
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Actual return date must be in YYYY-MM-DD format.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Damage charge must be a valid number.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error calculating return: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void processReturn() {
        try {
            if (cmbRentalId.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Please select a rental ID.");
                return;
            }
            if (iblActualReturnDatetxt.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Actual return date is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String rentalId = cmbRentalId.getSelectedItem().toString();
            LocalDate actualReturnDate = LocalDate.parse(iblActualReturnDatetxt.getText());

            double damageCharge = iblDamageChargetxt.getText().isBlank()
                    ? 0.0
                    : Double.parseDouble(iblDamageChargetxt.getText());

            boolean processed = rentalController.processReturn(
                    rentalId,
                    actualReturnDate,
                    iblCatDestxt.getText(),
                    iblDamageDescptxt.getText(),
                    damageCharge
            );

            if (processed) {
                JOptionPane.showMessageDialog(this, "Return processed successfully.");
                loadDropdowns();
                loadTable();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to process return.");
            }
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Actual return date must be in YYYY-MM-DD format.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Damage charge must be a valid number.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error processing return: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearForm() {
        iblActualReturnDatetxt.setText("");
        iblCatDestxt.setText("");
        iblDamageDescptxt.setText("");
        iblDamageChargetxt.setText("");
        iblCatLateFeeperdaytxt.setText("");
        iblLateFeetxt.setText("");
        iblTotalChargestxt.setText("");
        iblRefundtxt.setText("");
        if (cmbRentalId.getItemCount() > 0) {
            cmbRentalId.setSelectedIndex(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReturnView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnprocessReturn;
    private javax.swing.JComboBox<String> cmbRentalId;
    private javax.swing.JLabel iblActualReturnDate;
    private javax.swing.JTextField iblActualReturnDatetxt;
    private javax.swing.JLabel iblCatDes;
    private javax.swing.JTextField iblCatDestxt;
    private javax.swing.JLabel iblCatLateFeeperday;
    private javax.swing.JTextField iblCatLateFeeperdaytxt;
    private javax.swing.JLabel iblDamageCharge;
    private javax.swing.JTextField iblDamageChargetxt;
    private javax.swing.JLabel iblDamageDescp;
    private javax.swing.JTextField iblDamageDescptxt;
    private javax.swing.JButton iblDelete;
    private javax.swing.JLabel iblHeader;
    private javax.swing.JLabel iblLateFee;
    private javax.swing.JTextField iblLateFeetxt;
    private javax.swing.JLabel iblRefund;
    private javax.swing.JTextField iblRefundtxt;
    private javax.swing.JLabel iblRentalId;
    private javax.swing.JButton iblSave;
    private javax.swing.JLabel iblTotalCharges;
    private javax.swing.JTextField iblTotalChargestxt;
    private javax.swing.JButton iblUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReturn;
    // End of variables declaration//GEN-END:variables
}
