
package com.ijse.GearRentPro.view;

import com.ijse.GearRentPro.controller.UserController;
import com.ijse.GearRentPro.dto.UserDto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class UserView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserView.class.getName());
    private UserController userController = new UserController();

    /**
     * Creates new form UserView
     */
    public UserView() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblDelete = new javax.swing.JButton();
        iblUserId = new javax.swing.JLabel();
        iblPassword = new javax.swing.JLabel();
        iblRoleIdtxt = new javax.swing.JTextField();
        iblPasswordtxt = new javax.swing.JTextField();
        iblBranchId = new javax.swing.JLabel();
        iblRoleId = new javax.swing.JLabel();
        iblBranchIdtxt = new javax.swing.JTextField();
        iblUserIdtxt = new javax.swing.JTextField();
        iblUpdate = new javax.swing.JButton();
        iblUsername = new javax.swing.JLabel();
        iblUsernametxt = new javax.swing.JTextField();
        iblSave = new javax.swing.JButton();
        iblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iblDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblDelete.setText("Delete");
        iblDelete.addActionListener(this::iblDeleteActionPerformed);

        iblUserId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblUserId.setText("User ID");

        iblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblPassword.setText("Password");

        iblRoleIdtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblRoleIdtxt.addActionListener(this::iblRoleIdtxtActionPerformed);

        iblPasswordtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblPasswordtxt.addActionListener(this::iblPasswordtxtActionPerformed);

        iblBranchId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblBranchId.setText("Branch ID");

        iblRoleId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblRoleId.setText("Role ID");

        iblBranchIdtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblBranchIdtxt.addActionListener(this::iblBranchIdtxtActionPerformed);

        iblUserIdtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        iblUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblUpdate.setText("Update");
        iblUpdate.addActionListener(this::iblUpdateActionPerformed);

        iblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblUsername.setText("Username");

        iblUsernametxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblUsernametxt.addActionListener(this::iblUsernametxtActionPerformed);

        iblSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iblSave.setText("Save");
        iblSave.addActionListener(this::iblSaveActionPerformed);

        iblHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        iblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iblHeader.setText("Manage User");

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUser);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(iblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(iblRoleId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(iblUsername)
                                .addComponent(iblUserId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(iblBranchId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iblBranchIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblUsernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblPasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblRoleIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblUserIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(368, 368, 368))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iblSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iblHeader)
                .addGap(18, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblUserIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(iblUsername))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iblUsernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(iblUpdate)
                        .addComponent(iblSave)
                        .addComponent(iblDelete))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iblPassword)
                            .addComponent(iblPasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblRoleIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblRoleId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblBranchIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblBranchId))
                        .addGap(52, 52, 52)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnBack)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iblDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblDeleteActionPerformed
        deleteUser();
    }//GEN-LAST:event_iblDeleteActionPerformed

    private void iblRoleIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblRoleIdtxtActionPerformed

    }//GEN-LAST:event_iblRoleIdtxtActionPerformed

    private void iblPasswordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblPasswordtxtActionPerformed

    }//GEN-LAST:event_iblPasswordtxtActionPerformed

    private void iblBranchIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblBranchIdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblBranchIdtxtActionPerformed

    private void iblUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblUpdateActionPerformed
        updateUser();
    }//GEN-LAST:event_iblUpdateActionPerformed

    private void iblUsernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblUsernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iblUsernametxtActionPerformed

    private void iblSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblSaveActionPerformed
        saveUser();
    }//GEN-LAST:event_iblSaveActionPerformed

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        searchUser();
    }//GEN-LAST:event_tblUserMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            dispose();
            new MainDashboardView().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening User View : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void loadTable() {
        try {
            DefaultTableModel model = new DefaultTableModel(
                    new Object[]{"User ID", "Username", "Password", "Role ID", "Branch ID"},
                    0
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            tblUser.setModel(model);
            List<UserDto> users = userController.findAllUsers();
            for (UserDto user : users) {
                model.addRow(new Object[]{
                    user.getUserId(),
                    user.getUsername(),
                    user.getPassword(),
                    user.getRoleId(),
                    user.getBranchId()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading users: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void saveUser() {
        try {
            if (iblUserIdtxt.getText().isBlank() || iblUsernametxt.getText().isBlank() || iblPasswordtxt.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "User ID, username, and password are required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (iblRoleIdtxt.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Role ID is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            UserDto dto = new UserDto(
                    iblUserIdtxt.getText(),
                    iblUsernametxt.getText(),
                    iblPasswordtxt.getText(),
                    iblRoleIdtxt.getText(),
                    iblBranchIdtxt.getText()
            );

            boolean isSaved = userController.saveUser(dto);
            if (isSaved) {
                JOptionPane.showMessageDialog(this, "User saved successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save user.");
            }

            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving user: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateUser() {
        try {
            if (iblUserIdtxt.getText().isBlank() || iblUsernametxt.getText().isBlank() || iblPasswordtxt.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "User ID, username, and password are required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (iblRoleIdtxt.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Role ID is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            UserDto dto = new UserDto(
                    iblUserIdtxt.getText(),
                    iblUsernametxt.getText(),
                    iblPasswordtxt.getText(),
                    iblRoleIdtxt.getText(),
                    iblBranchIdtxt.getText()
            );

            boolean isUpdated = userController.updateUser(dto);
            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "User updated successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update user.");
            }

            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating user: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deleteUser() {
        try {
            String userId = iblUserIdtxt.getText();
            if (userId.isBlank()) {
                JOptionPane.showMessageDialog(this, "Please enter or select a user ID to delete.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            boolean isDeleted = userController.deleteUser(userId);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "User deleted successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete user.");
            }

            loadTable();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error deleting user: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void searchUser() {
        try {
            int selectedRow = tblUser.getSelectedRow();
            if (selectedRow < 0) {
                return;
            }

            String userId = tblUser.getValueAt(selectedRow, 0).toString();
            UserDto user = userController.findUser(userId);
            if (user == null) {
                JOptionPane.showMessageDialog(this, "User not found.");
                return;
            }

            iblUserIdtxt.setText(user.getUserId());
            iblUsernametxt.setText(user.getUsername());
            iblPasswordtxt.setText(user.getPassword());
            iblRoleIdtxt.setText(user.getRoleId());
            iblBranchIdtxt.setText(user.getBranchId());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error searching user: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearForm() {
        iblUserIdtxt.setText("");
        iblUsernametxt.setText("");
        iblPasswordtxt.setText("");
        iblRoleIdtxt.setText("");
        iblBranchIdtxt.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel iblBranchId;
    private javax.swing.JTextField iblBranchIdtxt;
    private javax.swing.JButton iblDelete;
    private javax.swing.JLabel iblHeader;
    private javax.swing.JLabel iblPassword;
    private javax.swing.JTextField iblPasswordtxt;
    private javax.swing.JLabel iblRoleId;
    private javax.swing.JTextField iblRoleIdtxt;
    private javax.swing.JButton iblSave;
    private javax.swing.JButton iblUpdate;
    private javax.swing.JLabel iblUserId;
    private javax.swing.JTextField iblUserIdtxt;
    private javax.swing.JLabel iblUsername;
    private javax.swing.JTextField iblUsernametxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables
}